In [1]:
import glob
import pandas as pd
import re
from bs4 import BeautifulSoup
import markdownify as md

from typing import List
from pydantic import BaseModel, Field
import instructor
from openai import OpenAI
from tqdm import tqdm
from zipfile import ZipFile

In [2]:
# 1. Define schema for categorized keywords
class JobKeywords(BaseModel):
    job_title: str = Field(description="Title of the job e.g., Assistant Professor of Economics")
    university: str = Field(description="Name of the university or institution offering the job, e.g., Salisbury University, or University of California, Berkeley")
    location: str = Field(description="Location of the job, e.g., Salisbury, MD, or Berkeley, CA")
    review_start: str = Field(description="Date from which they will begin reviewing applications (may be 'none'), e.g., September 11, 2026, or 2023-09-30")
    deadline: str = Field(description="Deadline for applying to the job (may be 'none'), e.g., September 11, 2026, or 2023-09-30")
    responsibilities: List[str] = Field(
        description="Key responsibilities or duties of the job (e.g., Undergraduate Teaching, Research, Publications, Service)"
    )
    preferred_qualifications: List[str] = Field(
        description="Preferred qualifications or experiences (e.g., Experience with Python, Strong communication skills)"
    )
    required_skills: List[str] = Field(
        description="Required technical skills, academic disciplines, or methodologies (e.g., Stata, Econometrics, Data Science)"
    )
    visa_sponsorship: str = Field(description="Visa sponsorship status, may or may not be mentioned. (e.g., Is eligible for H1B visa sponsorship, Not eligible, Not Mentioned)")

In [3]:
class RequiredDocuments(BaseModel):
    documents: List[str] = Field(description="List of required documents (e.g., Resume, Cover Letter, Transcripts, Teaching Statement, Research Statement, Diversity Statement, Teaching Portfolio, Letters of Recommendation)")

In [4]:
# 2. Initialize Instructor with local Ollama
client = instructor.from_openai(
    OpenAI(base_url="http://localhost:11434/v1", api_key="ollama"),
    mode=instructor.Mode.JSON
)

/opt/homebrew/Caskroom/miniconda/base/envs/scraping/lib/python3.12/site-packages/requests/__init__.py:92: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [5]:
# 4. Extract keywords
def extract_from_post(job_description):
    extracted = client.chat.completions.create(
        model="qwen2.5:3b",
        response_model=JobKeywords,
        messages=[
            {
                "role": "system",
                "content": "Extract key information accurately from the provided job description text."
            },
            {
                "role": "user",
                "content": job_description
            }
        ]
    )
    return extracted.model_dump()

In [6]:
# 4. Extract keywords
def extract_requirements_from_post(job_description):
    extracted = client.chat.completions.create(
        model="qwen2.5:3b",
        response_model=RequiredDocuments,
        messages=[
            {
                "role": "system",
                "content": "Extract required documents accurately from the provided job description text."
            },
            {
                "role": "user",
                "content": job_description
            }
        ]
    )
    return extracted.model_dump()

In [27]:
# Open the ZIP archive
with ZipFile('data/html_cache/cv1.zip', 'r') as zf:
    # Loop through all files in the ZIP folder
    for file_name in zf.namelist():
        # Optional: Filter for specific file types (e.g., text files)
        if file_name.endswith('.html'):
            print(f"--- Reading: {file_name} ---")

            # Open the specific file inside the ZIP
            with zf.open(file_name, 'r') as f:
                for line in f:
                    # Decode bytes to string and print
                    print(line.decode('utf-8').strip())

--- Reading: cv/205.html ---
<!DOCTYPE html><html lang="en-US" class="js"><head>

<title>Research Assistant - Tepper School of Business job with Carnegie Mellon University | 37989709</title>

KeyboardInterrupt:

In [9]:
files = glob.glob("data/html_cache/hedj/*.html")

In [10]:
attribs = ['job-header', 'jobLocation', 'jobAttrib', 'jobDesc']
info = []
for file in files:
    record = {"file": file, "text": "", "link": ""}
    with open(file, "r", encoding="utf-8") as f:
        html_content = f.read()
    soup = BeautifulSoup(html_content, "html.parser")
    for attrib_id in attribs:
        attrib_div = soup.find(id=attrib_id)
        if attrib_div:
            attrib = md.markdownify(str(attrib_div))
            record["text"] += attrib

    link_div = soup.find(id="js-applyurl", recursive=True)
    if link_div:
        # Get 'href' or fall back to custom attributes like 'data-orig-href'
        href = link_div.get("data-orig-href")
        record["link"] = href

    # Pattern handles arbitrary whitespace/tabs and captures the date string
    pattern = r'"datePosted"\s*:\s*"([^"]+)"'

    match = re.search(pattern, html_content)
    if match:
        date_posted = match.group(1)
        record["date_posted"] = date_posted

    info.append(record)

KeyboardInterrupt:

In [41]:
df = pd.DataFrame(info)

In [ ]:
keywords = []

In [37]:
correct_idx = [r['idx'] for r in keywords]
failed_idx = []

In [38]:
for idx, row in tqdm(df.iterrows()):
    if idx not in correct_idx:
        try:
            kw = extract_from_post(row["text"])
            kw['idx'] = idx
            keywords.append(kw)
        except Exception as e:
            print(f"Failed to process post at index {idx}: {e}")
            failed_idx.append(idx)
    else:
        print("Skipped post at index", idx)

0it [00:00, ?it/s]

Skipped post at index 0
Skipped post at index 1
Skipped post at index 2
Skipped post at index 3
Skipped post at index 4
Skipped post at index 5
Skipped post at index 6
Skipped post at index 7
Skipped post at index 8
Skipped post at index 9
Skipped post at index 10
Skipped post at index 11
Skipped post at index 12
Skipped post at index 13
Skipped post at index 14
Skipped post at index 15
Skipped post at index 16
Skipped post at index 17
Skipped post at index 18
Skipped post at index 19
Skipped post at index 20
Skipped post at index 21
Skipped post at index 22
Skipped post at index 23
Skipped post at index 24
Skipped post at index 25
Skipped post at index 26
Skipped post at index 27
Skipped post at index 28
Skipped post at index 29
Skipped post at index 30
Skipped post at index 31
Skipped post at index 32
Skipped post at index 33
Skipped post at index 34
Skipped post at index 35
Skipped post at index 36
Skipped post at index 37
Skipped post at index 38
Skipped post at index 39
Skipped post at index 40
Skipped post at index 41
Skipped post at index 42
Skipped post at index 43
Skipped post at index 44
Skipped post at index 45
Skipped post at index 46
Skipped post at index 47
Skipped post at index 48
Skipped post at index 49
Skipped post at index 50
Skipped post at index 51
Skipped post at index 52
Skipped post at index 53
Skipped post at index 54
Skipped post at index 55
Skipped post at index 56
Skipped post at index 57
Skipped post at index 58
Skipped post at index 59
Skipped post at index 60
Skipped post at index 61
Skipped post at index 62
Skipped post at index 63
Skipped post at index 64
Skipped post at index 65
Skipped post at index 66
Skipped post at index 67
Skipped post at index 68
Skipped post at index 69
Skipped post at index 70
Skipped post at index 71
Skipped post at index 72
Skipped post at index 73
Skipped post at index 74
Skipped post at index 75
Skipped post at index 76
Skipped post at index 77
Skipped post at index 78
Skipped post at index 79
Skipped post at index 80
Skipped post at index 81
Skipped post at index 82
Skipped post at index 83
Skipped post at index 84
Skipped post at index 85
Skipped post at index 86
Skipped post at index 87
Skipped post at index 88
Skipped post at index 89
Skipped post at index 90
Skipped post at index 91
Skipped post at index 92
Skipped post at index 93
Skipped post at index 94
Skipped post at index 95
Skipped post at index 96
Skipped post at index 97
Skipped post at index 98
Skipped post at index 99

101it [00:16,  6.18it/s]

Skipped post at index 101
Skipped post at index 102
Skipped post at index 103
Skipped post at index 104
Skipped post at index 105
Skipped post at index 106
Skipped post at index 107
Skipped post at index 108
Skipped post at index 109
Skipped post at index 110
Skipped post at index 111
Skipped post at index 112
Skipped post at index 113
Skipped post at index 114
Skipped post at index 115
Skipped post at index 116
Skipped post at index 117
Skipped post at index 118
Skipped post at index 119
Skipped post at index 120
Skipped post at index 121
Skipped post at index 122
Skipped post at index 123
Skipped post at index 124
Skipped post at index 125
Skipped post at index 126
Skipped post at index 127
Skipped post at index 128
Skipped post at index 129
Skipped post at index 130
Skipped post at index 131
Skipped post at index 132
Skipped post at index 133
Skipped post at index 134
Skipped post at index 135
Skipped post at index 136
Skipped post at index 137
Skipped post at index 138
Skipped post at index 139
Skipped post at index 140
Skipped post at index 141
Skipped post at index 142
Skipped post at index 143
Skipped post at index 144
Skipped post at index 145
Skipped post at index 146
Skipped post at index 147
Skipped post at index 148
Skipped post at index 149
Skipped post at index 150
Skipped post at index 151
Skipped post at index 152
Skipped post at index 153
Skipped post at index 154
Skipped post at index 155
Skipped post at index 156
Skipped post at index 157
Skipped post at index 158
Skipped post at index 159
Skipped post at index 160
Skipped post at index 161
Skipped post at index 162
Skipped post at index 163
Skipped post at index 164
Skipped post at index 165
Skipped post at index 166
Skipped post at index 167
Skipped post at index 168
Skipped post at index 169
Skipped post at index 170
Skipped post at index 171
Skipped post at index 172
Skipped post at index 173
Skipped post at index 174
Skipped post at index 175
Skipped post at index 176
Skipped post at index 177
Skipped post at index 178
Skipped post at index 179
Skipped post at index 180
Skipped post at index 181
Skipped post at index 182
Skipped post at index 183
Skipped post at index 184
Skipped post at index 185
Skipped post at index 186
Skipped post at index 187
Skipped post at index 188
Skipped post at index 189
Skipped post at index 190
Skipped post at index 191
Skipped post at index 192
Skipped post at index 193
Skipped post at index 194
Skipped post at index 195
Skipped post at index 196
Skipped post at index 197
Skipped post at index 198
Skipped post at index 199
Skipped post at index 200
Skipped post at index 201
Skipped post at index 202
Skipped post at index 203
Skipped post at index 204
Skipped post at index 205
Skipped post at index 206
Skipped post at index 207
Skipped post at index 208
Skipped post at index 209
Skipped post at index 210
Skipped post at index 211
Skipped post at index 212
Skipped post at index 213
Skipped post at index 214
Skipped post at index 215

245it [00:34,  7.06it/s]

Skipped post at index 217
Skipped post at index 218
Skipped post at index 219
Skipped post at index 220
Skipped post at index 221
Skipped post at index 222
Skipped post at index 223
Skipped post at index 224
Skipped post at index 225
Skipped post at index 226
Skipped post at index 227
Skipped post at index 228
Skipped post at index 229
Skipped post at index 230
Skipped post at index 231
Skipped post at index 232
Skipped post at index 233
Skipped post at index 234
Skipped post at index 235
Skipped post at index 236
Skipped post at index 237
Skipped post at index 238
Skipped post at index 239
Skipped post at index 240
Skipped post at index 241
Skipped post at index 242
Skipped post at index 243
Skipped post at index 244

In [19]:
keywords

[{'job_title': 'Assistant Professor of Economics',
  'university': 'Salisbury University',
  'location': 'Salisbury, MD',
  'review_start': '2026-09-11',
  'deadline': '2026-09-11',
  'responsibilities': ['Undergraduate Teaching',
   'Research',
   'Publications',
   'Service'],
  'preferred_qualifications': ['Evidence of teaching effectiveness at the undergraduate level',
   "A research pipeline appropriate to a candidate's career stage, with publications or working papers in progress",
   'Interest in developing applied, policy-relevant electives that engage students',
   'Ability to work with data and modern econometric or computational tools'],
  'required_skills': ['Ph.D. in Economics',
   'Demonstrated potential for high-quality research in the relevant field',
   'Demonstrated commitment to excellence in undergraduate teaching'],
  'visa_sponsorship': 'Not eligible',
  'idx': 0},
 {'job_title': 'Postdoctoral Fellow in Economic Science, Fall 2027',
  'university': 'Chapman University',
  'location': 'Orange, CA',
  'review_start': '2027-08-01',
  'deadline': '2027-08-01',
  'responsibilities': ['Design, program and run experiments using human subjects.',
   'Coordinate with ESI faculty on developing theory and design for novel experiments, and developing and writing grant proposals.',
   'Collect and analyze data on subject behavior.',
   'Prepare slides and manuscripts for presentation at conferences and publication in peer reviewed journals.'],
  'preferred_qualifications': [],
  'required_skills': ['PhD in Economics, any field, with an emphasis in experimental economics, awarded within the last 5 years.',
   'Programming skills in languages such as Z-Tree, Python, Stata, Mathematica, Otree.'],
  'visa_sponsorship': 'Not eligible',
  'idx': 1},
 {'job_title': 'Visiting Assistant Professor of Global Studies-Critical Political Economy',
  'university': 'Colby College',
  'location': 'Waterville, ME',
  'review_start': '2026-12-04',
  'deadline': '2026-12-31',
  'responsibilities': ['Teaching', 'Research', 'Service'],
  'preferred_qualifications': ['Experience in critical political economy',
   'Transdisciplinary teaching and research',
   'Strong commitment to critical perspectives and pedagogies of the Global South and underrepresented communities'],
  'required_skills': ['Strong teaching excellence'],
  'visa_sponsorship': 'Not eligible',
  'idx': 2},
 {'job_title': 'Lecturer in Public and International Affairs',
  'university': 'Princeton University',
  'location': 'Princeton, NJ',
  'review_start': '2026-03-19',
  'deadline': '',
  'responsibilities': ['Undergraduate Teaching',
   'Co-teaching in areas such as International Relations, International Development, Domestic Policy, Global Health, Psychology and Public Policy',
   'Economics and Public Policy'],
  'preferred_qualifications': [],
  'required_skills': ['Advanced degree or comparable experience in a relevant field'],
  'visa_sponsorship': 'Not eligible',
  'idx': 3},
 {'job_title': 'Assistant, Associate, or Full Professor in Emerging Fields (Business and Economics)',
  'university': 'University of Hong Kong (HKU)',
  'location': 'Hong Kong, Hong Kong',
  'review_start': '',
  'deadline': '',
  'responsibilities': ['Undergraduate Teaching',
   'Research',
   'Publications',
   'Service'],
  'preferred_qualifications': ['Experience with relevant technologies and methodologies',
   'Strong communication skills',
   'Ability to engage with diverse student and academic communities'],
  'required_skills': ['Research in emerging academic disciplines',
   'Teaching and mentorship in relevant fields',
   'Ability to engage in scholarly publications and collaboration',
   'Demonstrated ability to secure funding and support research initiatives'],
  'visa_sponsorship': 'Is eligible for H1B visa sponsorship',
  'idx': 4},
 {'job_title': 'Assistant/Associate Professor of Economics',
  'university': 'Coastal Carolina University',
  'location': 'Conway, SC',
  'review_start': '2026-11-06',
  'deadline': '2026-11-06',
  'responsibilities': ['Teaches students in the classroom, laboratory, and/or studio.',
   'Prepares content, syllabi, and University Moodle/curricular site for each course and/or lab assigned each semester.',
   'Calculates and assigns grades (e.g., mid-term and final) through established procedures listed in the Faculty Manual and University catalog.',
   'Tracks and reports absences as directed by the Office of the Registrar.',
   'Conducts research to create and add to knowledge in a field or produces creative work.',
   'Trains students in related research techniques and in creative production.',
   'Posts and holds regular office hours each week per College and University guidelines.',
   'Engages in University-related activities including committee assignments, meetings, ceremonies, events and scholarly pursuits as prescribed in the Faculty Manual.',
   'Performs other duties as assigned.'],
  'preferred_qualifications': ['PhD or DBA in economics, financial economics, or a closely related field from an AACSB or regionally-accredited institution.'],
  'required_skills': ['Strong potential for excellence in teaching.'],
  'visa_sponsorship': 'Yes',
  'idx': 5},
 {'job_title': 'Assistant Professor of Instruction - Quantitative Methods and Economics',
  'university': 'University of Texas at El Paso',
  'location': 'El Paso, TX',
  'review_start': '2026-10-15',
  'deadline': '2026-10-15',
  'responsibilities': ['Teach primarily undergraduate courses in quantitative methods and business statistics, and courses in economics as needed.',
   'Contribute to curriculum development and assessment in the quantitative core.',
   'Serve on departmental and college committees and participate in community outreach.'],
  'preferred_qualifications': ['Terminal degree from an AACSB-accredited institution.',
   'Prior experience teaching business statistics, econometrics, or quantitative methods at the undergraduate level, with documented evidence of teaching effectiveness.',
   'Competence with statistical and data analytics software used in instruction (e.g., R, Python, Stata, Excel).',
   'Demonstrated competence in the instructional use of artificial intelligence tools, including their use in course and assessment design and in preparing students to apply AI appropriately to quantitative analysis.',
   'Experience with online or hybrid course delivery, multi-section coordination, or assessment of learning.',
   'Capacity to contribute to graduate instruction in data analytics.'],
  'required_skills': ['A terminal degree (PhD or DBA) in economics, statistics, finance, or a closely related quantitative field. Candidates who are ABD will be considered provided the degree is completed by the appointment date.',
   'Demonstrated capacity for effective instruction in quantitative coursework.'],
  'visa_sponsorship': 'Is eligible for H1B visa sponsorship',
  'idx': 6},
 {'job_title': 'Assistant Professor - Economics',
  'university': 'Salisbury University',
  'location': 'Salisbury, MD',
  'review_start': '2026-09-11',
  'deadline': '2026-09-11',
  'responsibilities': ['carry a standard teaching load of 3-3 across undergraduate programs',
   'an active research program leading to peer-reviewed publications',
   'mentoring of undergraduate research and capstone projects',
   'service to the department, school, university, and profession'],
  'preferred_qualifications': ['Evidence of teaching effectiveness at the undergraduate level',
   "A research pipeline appropriate to a candidate's career stage with publications or working papers in progress",
   'Interest in developing applied, policy-relevant electives that engage students',
   'Ability to work with data and modern econometric or computational tools'],
  'required_skills': ['Ph.D. in Economics, or completed by appointment start date (ABD candidates with a clear completion timeline will be considered)',
   'Demonstrated potential for high-quality research in the relevant field',
   'Demonstrated commitment to excellence in undergraduate teaching'],
  'visa_sponsorship': 'Not eligible',
  'idx': 7},
 {'job_title': 'Assistant Professor Of Economics',
  'university': 'Bucknell University',
  'location': 'Lewisburg, PA',
  'review_start': '2026-11-15',
  'deadline': '2026-11-15',
  'responsibilities': ['Teach five courses per year, including intermediate macroeconomics and electives from a heterodox perspective',
   'Advises students',
   'Participates in departmental, university, or professional service'],
  'preferred_qualifications': ['Demonstrate expertise in heterodox economics',
   'Excellence in undergraduate teaching',
   'Potential for a strong program of scholarship',
   'Demonstrate excellence in student-centered teaching',
   'Support students from a wide range of backgrounds and experiences',
   'Value collaboration and interdisciplinarity'],
  'required_skills': ['Ph. D. in economics by the start of the appointment (or in the final stages if completed)',
   'Teaching portfolio including a statement of teaching philosophy, course evaluations and syllabi if available, and descriptions of efforts to support students from a wide variety of backgrounds in an inclusive manner',
   'Research statement and research sample'],
  'visa_sponsorship': 'Is eligible for H1B visa sponsorship',
  'idx': 8},
 {'job_title': 'Assistant Professor, Economics and Asian Studies',
  'university': 'Skidmore College',
  'location': 'Saratoga Springs, NY',
  'review_start': '2027-08-01',
  'deadline': '2026-11-30',
  'responsibilities': ['Teach 18 credits per academic year in Economics and Asian Studies',
   'Contribute to interdisciplinary offerings',
   'Develop a coherent research stream',
   'Advise students',
   'Participate in departmental service activities',
   'Play a critical role in building the Asian Studies program'],
  'preferred_qualifications': ['Research interest and teaching capability in economics and Asian studies relating to China and Asia',
   'Evidence of teaching experience and promise'],
  'required_skills': ['A minimum of a Ph. D. degree in Economics (OR with a dissertation defenses scheduled prior to the start of the fall semester 2027)',
   'Teaching statement',
   'Three reference letters as part of the application',
   'One research paper to serve as evidence of scholarly promise'],
  'visa_sponsorship': 'Not eligible',
  'idx': 9},
 {'job_title': 'Financial Economics Faculty (Tenure Track)',
  'university': 'New College of Florida',
  'location': 'Sarasota, FL',
  'review_start': '2026-10-23',
  'deadline': 'Continuous',
  'responsibilities': ['Teaching and Scholarship Expectations',
   'Overseeing the Bloomberg Finance Lab',
   'Teaching a range of finance-related courses',
   'Teaching Intermediate Microeconomics and Micro-econometrics',
   'Teaching additional electives in their area of expertise',
   'Serving as a mentor for independent study projects',
   'Supervising undergraduate theses or senior projects',
   'Publishing in reputable peer-reviewed journals and book chapters'],
  'preferred_qualifications': [],
  'required_skills': ['Broadly trained in Economics or Financial Economics',
   'Experience with Bloomberg Terminal facility',
   'Ability to supervise independent study projects',
   'Experience in teaching at the undergraduate level'],
  'visa_sponsorship': 'Not eligible',
  'idx': 10},
 {'job_title': 'Faculty Position in International Economics, Open Rank',
  'university': 'Georgetown University',
  'location': 'Doha, Qatar',
  'review_start': '2026-10-15',
  'deadline': '2026-10-15',
  'responsibilities': ['Undergraduate Teaching',
   'Research',
   'Publications',
   'Service'],
  'preferred_qualifications': ['Strong commitment to excellence in teaching and mentoring',
   'Strong and active research agenda',
   'Clear evidence of potential to establish a record of research'],
  'required_skills': ['Ph.D. in Economics',
   'Experience with Empirically Relevant Research'],
  'visa_sponsorship': 'Is eligible for H1B visa sponsorship',
  'idx': 11},
 {'job_title': 'Assistant Professor - Department of Economics',
  'university': 'John Jay College of Criminal Justice',
  'location': 'New York City, NY',
  'review_start': '2026-10-15',
  'deadline': '2026-11-01',
  'responsibilities': ['Teach at both the undergraduate and graduate levels',
   'Mentor undergraduate and graduate students',
   'Develop curricula',
   'Serve as course coordinator',
   'Interact effectively with colleagues'],
  'preferred_qualifications': [],
  'required_skills': ['Ph. D. degree in Economics or equivalent',
   'Ability to teach successfully',
   'Potential for scholarly productivity',
   'Willingness to participate in course and program development',
   'Ability to work with others for the good of the institution'],
  'visa_sponsorship': 'Not eligible',
  'idx': 12},
 {'job_title': 'Chair Professor - Economics',
  'university': 'FLAME University',
  'location': 'Pune, India',
  'review_start': '',
  'deadline': '',
  'responsibilities': ['Undergraduate Teaching',
   'Research',
   'Publications',
   'Service'],
  'preferred_qualifications': ['Experience with Python',
   'Strong communication skills'],
  'required_skills': ['Stata', 'Econometrics', 'Data Science'],
  'visa_sponsorship': 'Not eligible',
  'idx': 13}]

In [42]:
df_details = pd.DataFrame(keywords)

In [43]:
df_details

,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,idx
0,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"[Undergraduate Teaching, Research, Publication...",[Evidence of teaching effectiveness at the und...,"[Ph.D. in Economics, Demonstrated potential fo...",Not eligible,0
1,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"[Design, program and run experiments using hum...",[],"[PhD in Economics, any field, with an emphasis...",Not eligible,1
2,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"[Teaching, Research, Service]","[Experience in critical political economy, Tra...",[Strong teaching excellence],Not eligible,2
3,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,,"[Undergraduate Teaching, Co-teaching in areas ...",[],[Advanced degree or comparable experience in a...,Not eligible,3
4,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",,,"[Undergraduate Teaching, Research, Publication...",[Experience with relevant technologies and met...,"[Research in emerging academic disciplines, Te...",Is eligible for H1B visa sponsorship,4
...,...,...,...,...,...,...,...,...,...,...
329,Professor of the Practice of Global Economic D...,Boston University,"Boston, MA",none,2026-09-21,"[Teach courses in their areas of expertise, Ad...",[Experience with international economic develo...,[Being an international economist and distingu...,Not Mentioned,73
330,"Assistant Professor, Economics (Tenure-Track)",Minot State University,"Minot, ND",none,none,"[Undergraduate Teaching, Research, Service, Re...","[Experience with Python, Strong communication ...","[Stata, Econometrics, Data Science]",Not Mentioned,74
331,2026-27AY Quarterly Lecturer - Economics (Pool),Santa Clara University,"Santa Clara, CA",none,none,[Fulfilling all duties associated with these c...,[Undergraduate teaching experience],"[Experience with Economics, Ph. D. in Economics]",Not Mentioned,75
332,Business and Technology Adjunct Opportunities,University of Wisconsin - Parkside,"Kenosha, WI",none,none,"[* Accounting, * Data Analytics, * Finance, * ...",[],[],Not Mentioned,100
333,Associate/Full Professor,Johns Hopkins University,"Baltimore, MD",none,Open Until Filled,"[Undergraduate Teaching, Research, Service]","[Preeminent Expert in Field, Commitment to Exc...","[Research Excellence, Teaching Excellence, Aca...",Not Mentioned,216

In [44]:
merged = pd.merge(df, df_details, left_index=True, right_on='idx')
merged

,file,text,link,date_posted,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,idx
0,data/html_cache/hedj/205.html,Assistant Professor of Economics\n============...,https://marylandconnect.wd1.myworkdayjobs.com/...,2026-07-22 17:45:52.497,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"[Undergraduate Teaching, Research, Publication...",[Evidence of teaching effectiveness at the und...,"[Ph.D. in Economics, Demonstrated potential fo...",Not eligible,0
1,data/html_cache/hedj/74.html,"Postdoctoral Fellow in Economic Science, Fall ...",https://apply.interfolio.com/194065,2026-09-25 17:35:19.32,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"[Design, program and run experiments using hum...",[],"[PhD in Economics, any field, with an emphasis...",Not eligible,1
2,data/html_cache/hedj/23.html,Visiting Assistant Professor of Global Studies...,https://apply.interfolio.com/195065,2026-10-08 11:32:45.427,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"[Teaching, Research, Service]","[Experience in critical political economy, Tra...",[Strong teaching excellence],Not eligible,2
3,data/html_cache/hedj/194.html,Lecturer in Public and International Affairs\n...,https://www.click2apply.net/kNe4BNFDn2X4OHE6c2QNR,2026-08-06 13:26:41.55,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,,"[Undergraduate Teaching, Co-teaching in areas ...",[],[Advanced degree or comparable experience in a...,Not eligible,3
4,data/html_cache/hedj/244.html,HKU Professoriate Recruitment (Business and Ec...,https://secure.dc5.pageuppeople.com/apply/932/...,2020-11-06 12:00:11.74,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",,,"[Undergraduate Teaching, Research, Publication...",[Experience with relevant technologies and met...,"[Research in emerging academic disciplines, Te...",Is eligible for H1B visa sponsorship,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,data/html_cache/hedj/139.html,Assistant Professor (Tenure Track) - Economics...,https://apply.interfolio.com/188852,2026-09-05 18:17:26.873,Assistant Professor (Tenure Track) - Economics,DePaul University,"Chicago, IL",2027-07-01,2027-09-11,[Teach undergraduate and graduate courses in t...,[],[Ph.D. in Economics or closely related field b...,Not Mentioned,240
239,data/html_cache/hedj/142.html,Lecturer or Senior Lecturer in Economics\n====...,https://ukjobs.uky.edu/postings/647459,2026-09-04 08:54:25.533,Lecturer or Senior Lecturer in Economics,University of Kentucky,"Lexington, KY",2027-08-01,2027-08-01,"[Teaching in large-lecture sections, Teaching ...",[Experience with teaching large lecture format...,"[Ph. D. in Economics, Prior college/university...",Not Mentioned,241
240,data/html_cache/hedj/115.html,SNF Agora Academy Postdoctoral Fellowship - 20...,https://apply.interfolio.com/193231,2026-09-15 21:16:25.827,SNF Agora Institute - Postdoctoral Fellowship,Johns Hopkins University,"Baltimore, MD",,Open Until Filled,"[carry out their own research, participate in ...","[strong academic record, trajectory to contrib...","[doctorate in May 2025 or later, engage with t...",Not Mentioned,242
241,data/html_cache/hedj/103.html,TTU Post Doctoral Research Associate\n========...,https://apptrkr.com/9837874,2026-09-18 11:34:18.287,TTU Post Doctoral Research Associate,Texas Tech University,"Lubbock, TX",Not mentioned,Not mentioned,[Performs specialized Post Doctoral work in th...,[Demonstrated track record of published resear...,"[PhD in area of project specialization, Knowle...",Not Mentioned,243
242,data/html_cache/hedj/154.html,Peter B. Kenen Visiting Fellowship\n==========...,https://www.click2apply.net/wJedg5sDOwVpBTa5Tg4ja,2026-09-01 12:23:53.517,Peter B. Kenen Visiting Fellowship,Princeton University,"Princeton, NJ",Not specified in the text,Not specified in the text,[Pursue research on any topic in international...,[Current Ph.D. economist],[Must hold a full-time position in a universit...,Not eligible for visa sponsorship,244

In [45]:
merged_uniq = merged.drop_duplicates(subset=['file'], keep='last')
merged_uniq

,file,text,link,date_posted,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,idx
0,data/html_cache/hedj/205.html,Assistant Professor of Economics\n============...,https://marylandconnect.wd1.myworkdayjobs.com/...,2026-07-22 17:45:52.497,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"[Undergraduate Teaching, Research, Publication...",[Evidence of teaching effectiveness at the und...,"[Ph.D. in Economics, Demonstrated potential fo...",Not eligible,0
1,data/html_cache/hedj/74.html,"Postdoctoral Fellow in Economic Science, Fall ...",https://apply.interfolio.com/194065,2026-09-25 17:35:19.32,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"[Design, program and run experiments using hum...",[],"[PhD in Economics, any field, with an emphasis...",Not eligible,1
2,data/html_cache/hedj/23.html,Visiting Assistant Professor of Global Studies...,https://apply.interfolio.com/195065,2026-10-08 11:32:45.427,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"[Teaching, Research, Service]","[Experience in critical political economy, Tra...",[Strong teaching excellence],Not eligible,2
3,data/html_cache/hedj/194.html,Lecturer in Public and International Affairs\n...,https://www.click2apply.net/kNe4BNFDn2X4OHE6c2QNR,2026-08-06 13:26:41.55,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,,"[Undergraduate Teaching, Co-teaching in areas ...",[],[Advanced degree or comparable experience in a...,Not eligible,3
4,data/html_cache/hedj/244.html,HKU Professoriate Recruitment (Business and Ec...,https://secure.dc5.pageuppeople.com/apply/932/...,2020-11-06 12:00:11.74,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",,,"[Undergraduate Teaching, Research, Publication...",[Experience with relevant technologies and met...,"[Research in emerging academic disciplines, Te...",Is eligible for H1B visa sponsorship,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,data/html_cache/hedj/139.html,Assistant Professor (Tenure Track) - Economics...,https://apply.interfolio.com/188852,2026-09-05 18:17:26.873,Assistant Professor (Tenure Track) - Economics,DePaul University,"Chicago, IL",2027-07-01,2027-09-11,[Teach undergraduate and graduate courses in t...,[],[Ph.D. in Economics or closely related field b...,Not Mentioned,240
239,data/html_cache/hedj/142.html,Lecturer or Senior Lecturer in Economics\n====...,https://ukjobs.uky.edu/postings/647459,2026-09-04 08:54:25.533,Lecturer or Senior Lecturer in Economics,University of Kentucky,"Lexington, KY",2027-08-01,2027-08-01,"[Teaching in large-lecture sections, Teaching ...",[Experience with teaching large lecture format...,"[Ph. D. in Economics, Prior college/university...",Not Mentioned,241
240,data/html_cache/hedj/115.html,SNF Agora Academy Postdoctoral Fellowship - 20...,https://apply.interfolio.com/193231,2026-09-15 21:16:25.827,SNF Agora Institute - Postdoctoral Fellowship,Johns Hopkins University,"Baltimore, MD",,Open Until Filled,"[carry out their own research, participate in ...","[strong academic record, trajectory to contrib...","[doctorate in May 2025 or later, engage with t...",Not Mentioned,242
241,data/html_cache/hedj/103.html,TTU Post Doctoral Research Associate\n========...,https://apptrkr.com/9837874,2026-09-18 11:34:18.287,TTU Post Doctoral Research Associate,Texas Tech University,"Lubbock, TX",Not mentioned,Not mentioned,[Performs specialized Post Doctoral work in th...,[Demonstrated track record of published resear...,"[PhD in area of project specialization, Knowle...",Not Mentioned,243
242,data/html_cache/hedj/154.html,Peter B. Kenen Visiting Fellowship\n==========...,https://www.click2apply.net/wJedg5sDOwVpBTa5Tg4ja,2026-09-01 12:23:53.517,Peter B. Kenen Visiting Fellowship,Princeton University,"Princeton, NJ",Not specified in the text,Not specified in the text,[Pursue research on any topic in international...,[Current Ph.D. economist],[Must hold a full-time position in a universit...,Not eligible for visa sponsorship,244

In [47]:
merged_uniq.to_csv(
    "data/output.csv",
    index=False,
    lineterminator="\r\n",  # Ensures standard carriage return + line feed for multi-line cells
    encoding="utf-8",
)

In [8]:
merged_uniq = pd.read_csv("data/output.csv")

In [9]:
keywords = []

In [13]:
correct_idx = [r['idx'] for r in keywords]
failed_idx = []

In [14]:
for idx, row in tqdm(merged_uniq.iterrows()):
    if idx not in correct_idx:
        try:
            kw = extract_requirements_from_post(row["text"])
            kw['idx'] = idx
            keywords.append(kw)
        except Exception as e:
            print(f"Failed to process post at index {idx}: {e}")
            failed_idx.append(idx)
    else:
        print("Skipped post at index", idx)

0it [00:00, ?it/s]

Skipped post at index 0
Skipped post at index 1
Skipped post at index 2
Skipped post at index 3
Skipped post at index 4
Skipped post at index 5
Skipped post at index 6
Skipped post at index 7
Skipped post at index 8
Skipped post at index 9
Skipped post at index 10
Skipped post at index 11
Skipped post at index 12
Skipped post at index 13
Skipped post at index 14
Skipped post at index 15
Skipped post at index 16
Skipped post at index 17
Skipped post at index 18
Skipped post at index 19
Skipped post at index 20
Skipped post at index 21
Skipped post at index 22
Skipped post at index 23
Skipped post at index 24
Skipped post at index 25
Skipped post at index 26
Skipped post at index 27
Skipped post at index 28
Skipped post at index 29
Skipped post at index 30
Skipped post at index 31
Skipped post at index 32
Skipped post at index 33
Skipped post at index 34
Skipped post at index 35
Skipped post at index 36
Skipped post at index 37
Skipped post at index 38
Skipped post at index 39
Skipped post at index 40
Skipped post at index 41
Skipped post at index 42
Skipped post at index 43
Skipped post at index 44
Skipped post at index 45
Skipped post at index 46
Skipped post at index 47
Skipped post at index 48
Skipped post at index 49
Skipped post at index 50
Skipped post at index 51
Skipped post at index 52
Skipped post at index 53
Skipped post at index 54
Skipped post at index 55
Skipped post at index 56
Skipped post at index 57
Skipped post at index 58
Skipped post at index 59
Skipped post at index 60
Skipped post at index 61
Skipped post at index 62
Skipped post at index 63
Skipped post at index 64
Skipped post at index 65
Skipped post at index 66
Skipped post at index 67
Skipped post at index 68
Skipped post at index 69
Skipped post at index 70
Skipped post at index 71
Skipped post at index 72
Skipped post at index 73
Skipped post at index 74
Skipped post at index 75
Skipped post at index 76
Skipped post at index 77
Skipped post at index 78
Skipped post at index 79
Skipped post at index 80
Skipped post at index 81
Skipped post at index 82
Skipped post at index 83
Skipped post at index 84
Skipped post at index 85
Skipped post at index 86
Skipped post at index 87
Skipped post at index 88
Skipped post at index 89
Skipped post at index 90
Skipped post at index 91
Skipped post at index 92
Skipped post at index 93
Skipped post at index 94
Skipped post at index 95
Skipped post at index 96
Skipped post at index 97
Skipped post at index 98
Skipped post at index 99
Skipped post at index 100
Skipped post at index 101
Skipped post at index 102
Skipped post at index 103
Skipped post at index 104
Skipped post at index 105
Skipped post at index 106
Skipped post at index 107
Skipped post at index 108
Skipped post at index 109
Skipped post at index 110
Skipped post at index 111
Skipped post at index 112
Skipped post at index 113
Skipped post at index 114
Skipped post at index 115
Skipped post at index 116
Skipped post at index 117
Skipped post at index 118
Skipped post at index 119
Skipped post at index 120
Skipped post at index 121
Skipped post at index 122
Skipped post at index 123
Skipped post at index 124
Skipped post at index 125

127it [00:15,  8.11it/s]

Skipped post at index 127
Skipped post at index 128
Skipped post at index 129
Skipped post at index 130
Skipped post at index 131
Skipped post at index 132
Skipped post at index 133
Skipped post at index 134
Skipped post at index 135
Skipped post at index 136
Skipped post at index 137

139it [00:28,  4.31it/s]

Skipped post at index 139
Skipped post at index 140
Skipped post at index 141
Skipped post at index 142
Skipped post at index 143
Skipped post at index 144
Skipped post at index 145
Skipped post at index 146
Skipped post at index 147
Skipped post at index 148
Skipped post at index 149
Skipped post at index 150
Skipped post at index 151
Skipped post at index 152
Skipped post at index 153
Skipped post at index 154
Skipped post at index 155
Skipped post at index 156
Skipped post at index 157
Skipped post at index 158
Skipped post at index 159
Skipped post at index 160
Skipped post at index 161
Skipped post at index 162
Skipped post at index 163
Skipped post at index 164
Skipped post at index 165
Skipped post at index 166
Skipped post at index 167
Skipped post at index 168
Skipped post at index 169
Skipped post at index 170
Skipped post at index 171
Skipped post at index 172
Skipped post at index 173
Skipped post at index 174
Skipped post at index 175
Skipped post at index 176

178it [00:56,  2.47it/s]

Skipped post at index 178
Skipped post at index 179
Skipped post at index 180
Skipped post at index 181
Skipped post at index 182
Skipped post at index 183
Skipped post at index 184
Skipped post at index 185
Skipped post at index 186
Skipped post at index 187
Skipped post at index 188
Skipped post at index 189
Skipped post at index 190
Skipped post at index 191
Skipped post at index 192
Skipped post at index 193
Skipped post at index 194
Skipped post at index 195
Skipped post at index 196
Skipped post at index 197
Skipped post at index 198
Skipped post at index 199
Skipped post at index 200
Skipped post at index 201
Skipped post at index 202
Skipped post at index 203
Skipped post at index 204
Skipped post at index 205
Skipped post at index 206
Skipped post at index 207
Skipped post at index 208
Skipped post at index 209
Skipped post at index 210
Skipped post at index 211
Skipped post at index 212
Skipped post at index 213
Skipped post at index 214
Skipped post at index 215
Skipped post at index 216
Skipped post at index 217
Skipped post at index 218
Skipped post at index 219
Skipped post at index 220
Skipped post at index 221
Skipped post at index 222
Skipped post at index 223
Skipped post at index 224
Skipped post at index 225
Skipped post at index 226
Skipped post at index 227
Skipped post at index 228
Skipped post at index 229
Skipped post at index 230
Skipped post at index 231
Skipped post at index 232
Skipped post at index 233
Skipped post at index 234
Skipped post at index 235
Skipped post at index 236
Skipped post at index 237
Skipped post at index 238
Skipped post at index 239
Skipped post at index 240
Skipped post at index 241

245it [01:10,  3.46it/s]

Skipped post at index 243
Skipped post at index 244

In [15]:
df_requirements = pd.DataFrame(keywords)
df_requirements

                                             documents  idx
0    [Curriculum Vitae, Cover Letter, Job Market Pa...    0
1    [Statement of interest, CV, Job Market Paper, ...    1
2    [Resume, Cover Letter, Curriculum Vitae, State...    2
3    [Curriculum Vitae, Cover Letter, Teaching Stat...    3
4    [Resume, Cover Letter, Research Statement, Tea...    4
..                                                 ...  ...
240                             [Resume, Cover Letter]  244
241                                 [Curriculum Vitae]  126
242  [Letter of Application, Curriculum Vitae, Stat...  138
243  [Resume/CV, Cover Letter, Contact Information ...  177
244  [CV, Research statement (max 1,500 words), Wri...  242

[245 rows x 2 columns]

In [16]:
merged2 = pd.merge(merged_uniq, df_requirements, left_on='idx', right_on='idx')
merged2

,file,text,link,date_posted,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,idx,documents
0,data/html_cache/hedj/205.html,Assistant Professor of Economics\n============...,https://marylandconnect.wd1.myworkdayjobs.com/...,2026-07-22 17:45:52.497,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"['Undergraduate Teaching', 'Research', 'Public...",['Evidence of teaching effectiveness at the un...,"['Ph.D. in Economics', 'Demonstrated potential...",Not eligible,0,"[Curriculum Vitae, Cover Letter, Job Market Pa..."
1,data/html_cache/hedj/74.html,"Postdoctoral Fellow in Economic Science, Fall ...",https://apply.interfolio.com/194065,2026-09-25 17:35:19.32,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"['Design, program and run experiments using hu...",[],"['PhD in Economics, any field, with an emphasi...",Not eligible,1,"[Statement of interest, CV, Job Market Paper, ..."
2,data/html_cache/hedj/23.html,Visiting Assistant Professor of Global Studies...,https://apply.interfolio.com/195065,2026-10-08 11:32:45.427,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"['Teaching', 'Research', 'Service']","['Experience in critical political economy', '...",['Strong teaching excellence'],Not eligible,2,"[Resume, Cover Letter, Curriculum Vitae, State..."
3,data/html_cache/hedj/194.html,Lecturer in Public and International Affairs\n...,https://www.click2apply.net/kNe4BNFDn2X4OHE6c2QNR,2026-08-06 13:26:41.55,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,NaN,"['Undergraduate Teaching', 'Co-teaching in are...",[],['Advanced degree or comparable experience in ...,Not eligible,3,"[Curriculum Vitae, Cover Letter, Teaching Stat..."
4,data/html_cache/hedj/244.html,HKU Professoriate Recruitment (Business and Ec...,https://secure.dc5.pageuppeople.com/apply/932/...,2020-11-06 12:00:11.74,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",NaN,NaN,"['Undergraduate Teaching', 'Research', 'Public...",['Experience with relevant technologies and me...,"['Research in emerging academic disciplines', ...",Is eligible for H1B visa sponsorship,4,"[Resume, Cover Letter, Research Statement, Tea..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,data/html_cache/hedj/139.html,Assistant Professor (Tenure Track) - Economics...,https://apply.interfolio.com/188852,2026-09-05 18:17:26.873,Assistant Professor (Tenure Track) - Economics,DePaul University,"Chicago, IL",2027-07-01,2027-09-11,"[""Teach undergraduate and graduate courses in ...",[],['Ph.D. in Economics or closely related field ...,Not Mentioned,240,"[Cover Letter, C.V., Research Statement, Teach..."
241,data/html_cache/hedj/142.html,Lecturer or Senior Lecturer in Economics\n====...,https://ukjobs.uky.edu/postings/647459,2026-09-04 08:54:25.533,Lecturer or Senior Lecturer in Economics,University of Kentucky,"Lexington, KY",2027-08-01,2027-08-01,"['Teaching in large-lecture sections', ""Teachi...",['Experience with teaching large lecture forma...,"['Ph. D. in Economics', 'Prior college/univers...",Not Mentioned,241,"[Cover Letter, CV, Statement of Teaching Philo..."
242,data/html_cache/hedj/115.html,SNF Agora Academy Postdoctoral Fellowship - 20...,https://apply.interfolio.com/193231,2026-09-15 21:16:25.827,SNF Agora Institute - Postdoctoral Fellowship,Johns Hopkins University,"Baltimore, MD",NaN,Open Until Filled,"['carry out their own research', 'participate ...","['strong academic record', 'trajectory to cont...","['doctorate in May 2025 or later', 'engage wit...",Not Mentioned,242,"[CV, Research statement (max 1,500 words), Wri..."
243,data/html_cache/hedj/103.html,TTU Post Doctoral Research Associate\n========...,https://apptrkr.com/9837874,2026-09-18 11:34:18.287,TTU Post Doctoral Research Associate,Texas Tech University,"Lubbock, TX",Not mentioned,Not mentioned,['Performs specialized Post Doctoral work in t...,['Demonstrated track record of published resea...,"['PhD in area of project specialization', 'Kno...",Not Mentioned,243,"[Resume, Cover Letter]"
244,data/html_cache/hedj/154.html,Peter B. Kenen Visiting Fellowship\n==========...,https://www.click2apply.net/wJedg5sDOwVpBTa5Tg4ja,2026-09-01 12:23:53.517,Peter B. Kenen Visiting Fellowship,Princeton University,"Princeton, NJ",Not specified in the text,Not specified in the text,['Pursue research on any topic in internationa...,['Current Ph.D. economist'],['Must hold a full-time position in a universi...,Not eligible for visa sponsorship,244,"[Resume, Cover Letter]"

In [19]:
# 1. Convert to datetime, turning malformed rows into NaT (Not a Time)
review_start = pd.to_datetime(merged2["review_start"], errors="coerce", format="mixed")
deadline = pd.to_datetime(merged2["deadline"], errors="coerce", format="mixed")

# 2. Format the valid dates to your fixed format (e.g., 'YYYY-MM-DD')
formatted_review_start = review_start.dt.strftime("%Y-%m-%d")
formatted_deadline = deadline.dt.strftime("%Y-%m-%d")

In [20]:
# 3. Fill the NaT gaps with the original text column
formatted_review_start = formatted_review_start.fillna(merged2["review_start"])
formatted_deadline = formatted_deadline.fillna(merged2["deadline"])

In [21]:
merged2["review_start"] = formatted_review_start
merged2["deadline"] = formatted_deadline
merged2

,file,text,link,date_posted,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,idx,documents
0,data/html_cache/hedj/205.html,Assistant Professor of Economics\n============...,https://marylandconnect.wd1.myworkdayjobs.com/...,2026-07-22 17:45:52.497,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"['Undergraduate Teaching', 'Research', 'Public...",['Evidence of teaching effectiveness at the un...,"['Ph.D. in Economics', 'Demonstrated potential...",Not eligible,0,"[Curriculum Vitae, Cover Letter, Job Market Pa..."
1,data/html_cache/hedj/74.html,"Postdoctoral Fellow in Economic Science, Fall ...",https://apply.interfolio.com/194065,2026-09-25 17:35:19.32,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"['Design, program and run experiments using hu...",[],"['PhD in Economics, any field, with an emphasi...",Not eligible,1,"[Statement of interest, CV, Job Market Paper, ..."
2,data/html_cache/hedj/23.html,Visiting Assistant Professor of Global Studies...,https://apply.interfolio.com/195065,2026-10-08 11:32:45.427,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"['Teaching', 'Research', 'Service']","['Experience in critical political economy', '...",['Strong teaching excellence'],Not eligible,2,"[Resume, Cover Letter, Curriculum Vitae, State..."
3,data/html_cache/hedj/194.html,Lecturer in Public and International Affairs\n...,https://www.click2apply.net/kNe4BNFDn2X4OHE6c2QNR,2026-08-06 13:26:41.55,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,NaN,"['Undergraduate Teaching', 'Co-teaching in are...",[],['Advanced degree or comparable experience in ...,Not eligible,3,"[Curriculum Vitae, Cover Letter, Teaching Stat..."
4,data/html_cache/hedj/244.html,HKU Professoriate Recruitment (Business and Ec...,https://secure.dc5.pageuppeople.com/apply/932/...,2020-11-06 12:00:11.74,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",NaN,NaN,"['Undergraduate Teaching', 'Research', 'Public...",['Experience with relevant technologies and me...,"['Research in emerging academic disciplines', ...",Is eligible for H1B visa sponsorship,4,"[Resume, Cover Letter, Research Statement, Tea..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,data/html_cache/hedj/139.html,Assistant Professor (Tenure Track) - Economics...,https://apply.interfolio.com/188852,2026-09-05 18:17:26.873,Assistant Professor (Tenure Track) - Economics,DePaul University,"Chicago, IL",2027-07-01,2027-09-11,"[""Teach undergraduate and graduate courses in ...",[],['Ph.D. in Economics or closely related field ...,Not Mentioned,240,"[Cover Letter, C.V., Research Statement, Teach..."
241,data/html_cache/hedj/142.html,Lecturer or Senior Lecturer in Economics\n====...,https://ukjobs.uky.edu/postings/647459,2026-09-04 08:54:25.533,Lecturer or Senior Lecturer in Economics,University of Kentucky,"Lexington, KY",2027-08-01,2027-08-01,"['Teaching in large-lecture sections', ""Teachi...",['Experience with teaching large lecture forma...,"['Ph. D. in Economics', 'Prior college/univers...",Not Mentioned,241,"[Cover Letter, CV, Statement of Teaching Philo..."
242,data/html_cache/hedj/115.html,SNF Agora Academy Postdoctoral Fellowship - 20...,https://apply.interfolio.com/193231,2026-09-15 21:16:25.827,SNF Agora Institute - Postdoctoral Fellowship,Johns Hopkins University,"Baltimore, MD",NaN,Open Until Filled,"['carry out their own research', 'participate ...","['strong academic record', 'trajectory to cont...","['doctorate in May 2025 or later', 'engage wit...",Not Mentioned,242,"[CV, Research statement (max 1,500 words), Wri..."
243,data/html_cache/hedj/103.html,TTU Post Doctoral Research Associate\n========...,https://apptrkr.com/9837874,2026-09-18 11:34:18.287,TTU Post Doctoral Research Associate,Texas Tech University,"Lubbock, TX",Not mentioned,Not mentioned,['Performs specialized Post Doctoral work in t...,['Demonstrated track record of published resea...,"['PhD in area of project specialization', 'Kno...",Not Mentioned,243,"[Resume, Cover Letter]"
244,data/html_cache/hedj/154.html,Peter B. Kenen Visiting Fellowship\n==========...,https://www.click2apply.net/wJedg5sDOwVpBTa5Tg4ja,2026-09-01 12:23:53.517,Peter B. Kenen Visiting Fellowship,Princeton University,"Princeton, NJ",Not specified in the text,Not specified in the text,['Pursue research on any topic in internationa...,['Current Ph.D. economist'],['Must hold a full-time position in a universi...,Not eligible for visa sponsorship,244,"[Resume, Cover Letter]"

In [26]:
merged2['status'] = '...'
merged2.to_csv(
    "data/hedjobs.csv",
    index=False,
    lineterminator="\r\n",  # Ensures standard carriage return + line feed for multi-line cells
    encoding="utf-8",
)

In [24]:
docs = merged2["documents"]
documents = set()
for ds in docs:
    # s = [str(i) for i in ds[1:-1].split(',')]
    documents.update(ds)
documents

{'2 publications or writing samples',
 '2 recommendation letters',
 '3 Reference Letters (contact information only)',
 "A cover letter addressing the position requirements listed above as well as the ways they might contribute to and further the College's Jesuit, undergraduate liberal arts college and its core commitment to creating a community where every individual feels empowered to contribute their talents and perspectives.",
 'A curriculum vitae',
 'A letter of application detailing your interest in the position and how you meet the required qualifications (max. 2 pages) (as one complete document).',
 'A statement of teaching philosophy',
 "A statement of teaching philosophy, including evidence of teaching effectiveness, supporting URI's strategic priorities of cultivating a diverse, inclusive, equitable, and accessible learning environment (max. 3 pages) (as one complete document).",
 'A statement of your teaching philosophy and interests, with particular emphasis on how you utilize evidence-based teaching strategies to foster inclusive, high-belonging classroom environments.',
 'ABD Candidates - a letter from their dissertation chair or department chair certifying ABD status and their anticipated dissertation timeline',
 'Academic References',
 'Academic Writing Example',
 'Additional Research Papers',
 'Additional Working Papers (if applicable)',
 'Additional Working Papers (optional)',
 'Authorization to Release Information Form',
 'C.V.',
 'CV',
 'CV / Resume',
 'CV/Resume',
 'Combined Research, Teaching, and Mentoring Statement',
 'Completed AUC Personnel Information Form',
 'Completed AUC Personnel Information Form (PIF)',
 'Confidential Letter of Recommendation or Evaluation',
 'Contact Details for Three Academic References',
 'Contact Details for Three References',
 'Contact Information for 2-3 Referees',
 'Contact Information for 3 References',
 'Contact Information for Five Professional References',
 'Contact Information for One Reference',
 'Contact Information for Three Professional References',
 'Contact Information for Three References',
 'Contact Information for at least 3 References',
 'Contact Information including email addresses for three reference letters',
 'Contact Information of Three Professional References',
 'Contact and Further Information',
 'Contact information for at least three references',
 'Contact information for four work-related references',
 'Contact information for references (six references will be solicited from finalists)',
 'Contact information for three professional references',
 'Contact information for three references',
 'Copies of Publications and/or Working Papers',
 'Copies of Recent Research Papers',
 'Copies of undergraduate and graduate transcripts',
 'Copy of Teaching Evaluations',
 'Cover Letter',
 'Cover Letter (Optional)',
 'Cover Letter - Please include relevant experience with conducting past RCTs (including corresponding roles)',
 'Cover Letter describing qualifications for the position, research interests, and teaching experience',
 'Cover Letters',
 'Cover letter',
 'Cover letter describing research interests, current projects, and fit with the PPE Program',
 'Cover letter detailing interest in the position',
 'Cover letter outlining qualifications and specific interest in the position, including experience or interest in integrating AI and data analytics with Economics and/or business education',
 'Cover letter outlining research, teaching, and leadership vision',
 'Cover letter summarizing qualifications, teaching interests, and research interests',
 'Cover letter summarizing your qualifications and interest',
 'Current CV',
 'Current Curriculum Vitae',
 'Current Curriculum vitae',
 'Current curriculum vitae',
 'Curriculum Vita',
 'Curriculum Vita (include a recent photo; state citizenship; and links to Google Scholar & Scopus and LinkedIn profile)',
 'Curriculum Vitae',
 'Curriculum Vitae (Resume)',
 'Curriculum Vitae - Your most recently updated C.V.',
 'Curriculum Vitae - Your most recently updated CV',
 'Curriculum Vitae including names and contact information of three references (do not send letters of reference with initial application) (as one complete document).',
 'Curriculum vitae',
 'Curriculum vitae (CV)',
 'Curriculum vitae including a list of courses taught',
 'Curriculum-Vitae',
 'Date of Birth',
 'Description of Research Plans',
 'Description of Teaching',
 'Detailed Resume',
 'Dissertation',
 'Dissertation Abstract',
 'Diversity Statement',
 'Education Transcripts',
 'Evidence of Classroom Teaching Effectiveness (e.g., Course Evaluations)',
 'Evidence of Demonstrated/Excellence in Undergraduate Instruction',
 'Evidence of Effective Teaching',
 'Evidence of Research (e.g., published papers, working papers, or research manuscript). Upload as Research Interest',
 'Evidence of Teaching Effectiveness',
 'Evidence of Teaching Effectiveness (e.g., Sample Syllabi and Teaching Evaluations)',
 'Evidence of Teaching Effectiveness (e.g., Student Evaluations, Peer Observations, Sample Materials)',
 'Evidence of Teaching Effectiveness (such as a teaching statement and teaching evaluations)',
 'Evidence of Teaching Effectiveness (teaching statement, syllabi, course list, course evaluations)',
 'Evidence of Teaching Effectiveness: (such as teaching evaluations, peer observations, letters addressing teaching ability, or other relevant materials). Upload as Additional Documents',
 'Evidence of Teaching Excellence',
 'Evidence of Teaching Excellence (Teaching Statement, Sample Assignment)',
 'Evidence of Teaching Excellence (e.g., Course Evaluations)',
 'Evidence of Teaching Excellence (if available)',
 'Evidence of Teaching Experience and Effectiveness',
 'Evidence of Teaching Performance (if available)',
 'Evidence of Teaching and Research Effectiveness',
 'Evidence of effective teaching including a statement of teaching philosophy, a list of courses taught, and student evaluations',
 'Evidence of research such as a job market paper',
 'Evidence of teaching effectiveness',
 'Evidence of teaching excellence, preferably samples of teaching evaluations',
 'Example of Research Paper',
 'Examples of Teaching Evaluations',
 'Faculty Application',
 'Graduate School Transcripts',
 'Graduate Transcript',
 'Graduate Transcript(s)',
 'Graduate Transcripts',
 'Graduate Transcripts (unofficial acceptable)',
 'Graduate transcript',
 'Graduate transcripts',
 'Highest Degree Level',
 'Holistic Statement on Teaching and Student Success',
 'Job Market Paper',
 'Job Market Paper and Research Papers',
 'Job Market Paper and/or Representative Research',
 'Job Market Papers',
 'Job market paper',
 'Job market paper and/or representative research',
 'Job market paper or other writing sample',
 'Job market research paper in economics',
 'Job-Market Paper',
 'Letter describing interest in and qualifications',
 'Letter of Application',
 'Letter of Interest',
 'Letter of Promotion from Academic Institution for Associate or Full Professor positions',
 'Letter of Recommendation',
 'Letter of application',
 'Letter of application describing relevant experience and interest in the position',
 'Letter of interest',
 'Letters of Recommendation',
 'Letters of Recommendation (names and contact information provided)',
 'Letters of Recommendation (optional if provided)',
 'Letters of Recommendation (separate submission required)',
 'Letters of Reference',
 'Letters-of-Recommendation',
 'List of Professional References',
 'List of Recent Publications or Working Papers',
 'List of References',
 'List of Three References',
 'List of Two References',
 'List-of-Publications',
 'Most Recent Student Evaluations of Teaching',
 'Name and Contact Information of References',
 'Names and Contact Information for 3 References',
 'Names and Contact Information for Three Professional References',
 'Names and Contact Information for Three References',
 'Names and Contact Information for at least Three Individuals Who Can Provide a Letter of Recommendation',
 'Names and contact information for three references',
 'Names and contact information of 3-5 referees',
 'Names and contact information of three references',
 'Names of References',
 'Names of Three References',
 'Names of three individuals who can provide letters of recommendation',
 'Names of three references',
 'Names, phone numbers, and email addresses of at least 3 references',
 'Names, positions, and email addresses for two academic references',
 'Narrative of Administrative and Leadership Philosophy including a statement of past and proposed efforts to enhance diversity as well as the names, addresses, phone numbers and email addresses of at least three professional references who may be contacted, with permission of the candidate, following initial evaluations by the search committee',
 'Notice of E-Verify Participation',
 'Official Copy of Ph. D. Diploma',
 'Official Copy of PhD Diploma',
 'Official Graduate School Transcripts',
 'Official summaries of teaching evaluations',
 'Official transcript',
 'One Article-Length Writing Sample',
 'One Recent Research Paper',
 'One Working Paper',
 'One or Two Representative Research Papers',
 'One or Two Research Papers',
 'One or at most Two Research Papers',
 'One or at most two research papers',
 'One or more recent papers',
 'One to Two Research Papers',
 'One-page statement on research interests',
 'One-page statement on teaching philosophy',
 'Optional: Other Relevant Documents',
 'Optional: Representative Sample of Recent Scholarly Writing',
 'Personal Statement',
 'Ph. D. Degree',
 'Ph. D. in Economics, Business Law, Public Policy, or Related Field',
 'Ph.D. in Economics Certificate',
 'PhD applicants: Dissertation Prospectus or Research Statement (up to 10-15 pages)',
 'Portfolio (no more than 20 pages long that includes representative professional work depicting evidence of research, teaching activities, a narrative of administrative and leadership philosophy including a statement of past and proposed efforts to enhance diversity as well as the names, addresses, phone numbers, and email addresses of at least three professional references who may be contacted, with permission of the candidate, following initial evaluations by the search committee)',
 'Portfolio (no more than 20 pages long) that includes representative professional work depicting evidence of research, teaching activities;',
 'Portfolio (representative professional work)',
 'Post-MFA applicants: Project description (up to 2-5 pages) and additional material (based on the type of applicant – Writers, Visual Artists, Theatre Artists)',
 'Professional References',
 'Proof of Ph.D. or Ed. D.',
 'Proof of PhD Completion or a Letter from the Dissertation Advisor',
 'Publications or copies of creative works, if applicable',
 'Recent Papers',
 'Recent Publication or Job Market Paper',
 'Recent example of research (job paper)',
 'Recommendation Letters',
 'Reference list (at least three professional references and contact information)',
 'References',
 'References (3)',
 'References (Contact Information)',
 'References (Names and Contact Information)',
 'References (list of three names)',
 'References Contact Information',
 'References Letters',
 'References List',
 "References' Contact Information",
 'Rejection Letters/Closing Letters',
 'Religious Affiliation Form',
 'Representative Professional Work',
 'Representative Research Paper or Writing Sample',
 'Representative Sample of Research',
 'Representative Sample of Research Publications',
 'Representative publications',
 'Research Agenda',
 'Research Paper',
 'Research Paper - Job Market Paper',
 'Research Papers',
 'Research Papers and Publications',
 'Research Papers or Published Work',
 'Research Philosophy and Plans',
 'Research Proposal (maximum 5 double-spaced pages)',
 'Research Proposal or Statement',
 'Research Publication or Job Market Paper',
 'Research Sample',
 'Research Statement',
 'Research and Teaching Statement',
 'Research and Teaching statements',
 'Research sample',
 'Research statement',
 'Research statement (max 1,500 words)',
 'Research-Proposal',
 'Resume',
 'Resume or C.V.',
 'Resume or CV',
 'Resume or Curriculum Vitae',
 'Resume/CV',
 'Resume/Curriculum Vitae',
 'Resumes',
 'Resumé',
 'Resumé/CV',
 'Right to Work Notice',
 'Résumé',
 'Sample Course Syllabus/Syllabi',
 'Sample Exams and Course Syllabi',
 'Sample of Current Research (up to three representative publications)',
 'Sample of Recent Scholarship',
 'Sample of Research',
 'Sample of current research (up to three representative publications)',
 'Samples of Written Work',
 'Scholarly activity statement',
 'Service Philosophy and Plans',
 'Service Statement',
 'Service statement',
 'Specific Evidence of Teaching Experience and Effectiveness',
 'Start-date preferences and visa sponsorship information',
 'Statement Regarding Research Plans',
 "Statement explaining how your teaching, research, mentoring, and/or service experience would contribute both to the program and to Tufts University's efforts at supporting a culture of diversity, equity and inclusion",
 'Statement of Current Research Interest',
 'Statement of Current and Future Research Plans',
 'Statement of Extension or Outreach Philosophy',
 'Statement of Professional and/or Scholarly Achievement and Activity',
 'Statement of Purpose outlining research interests and teaching experience',
 'Statement of Research',
 'Statement of Research Experience and Interests',
 'Statement of Research Interests',
 'Statement of Research Interests and Teaching Philosophy',
 'Statement of Research and Teaching Interests',
 'Statement of Teaching',
 'Statement of Teaching Interest',
 'Statement of Teaching Interests',
 'Statement of Teaching Philosophy',
 'Statement of Teaching Philosophy and Experience',
 'Statement of Teaching Philosophy and Interests',
 'Statement of Teaching and Mentoring',
 'Statement of Teaching and Mentoring (including Teaching Evaluations, if available)',
 'Statement of University and Public Service',
 'Statement of interest',
 'Statement of research',
 'Statement of research interests and philosophy',
 'Statement of research interests and plans',
 'Statement of teaching',
 'Statement of teaching interests',
 'Statement of teaching philosophy',
 'Statement of teaching philosophy and current research agenda',
 'Statement of teaching philosophy, including a description of any use of emerging technologies or data-driven approaches in teaching',
 'Statement on Research',
 'Statement on Research Philosophy',
 'Statement on Service',
 'Statement on Teaching Philosophy',
 'Statement on the Integration of Teaching and Research',
 'Statements of Commitment to Inclusive Excellence',
 'Statements of research and teaching',
 'Student Success Statement',
 'Summary of Teaching Evaluations',
 'Syllabi of Courses Taught (if available)',
 'Teaching Dossier',
 'Teaching Effectiveness Evidence (e.g., recent course evaluations)',
 'Teaching Evaluations',
 'Teaching Evaluations (if applicable)',
 'Teaching Evaluations (if available)',
 'Teaching Evaluations - Please provide teaching evaluations for most recent two semesters of non-Summer, non-Teaching Assistant positions (if available, otherwise include any evaluations)',
 'Teaching Evaluations and/or Observations',
 'Teaching Evidence',
 'Teaching Philosophy Statement',
 'Teaching Philosophy and Plans',
 'Teaching Philosophy and Practice Statement',
 'Teaching Portfolio',
 'Teaching Portfolios',
 'Teaching Sample or Documentation of Teaching Effectiveness',
 'Teaching Statement',
 'Teaching Statement and Evaluations (if available)',
 'Teaching Statement/Philosophy',
 'Teaching and Mentoring Statement',
 'Teaching dossier',
 'Teaching evaluations',
 'Teaching portfolio',
 'Teaching statement',
 'Teaching/advising statement',
 'Three (3) Confidential letters of recommendation',
 'Three (3) professional reference letters',
 'Three Confidential Letter of References',
 'Three Confidential Letters of Recommendation',
 'Three Confidential Letters of Reference',
 'Three Confidential Reference Letters',
 'Three Confidential References',
 'Three Letters of Recommendation',
 'Three Letters of Reference',
 'Three Reference Letters',
 'Three References (contact information)',
 'Three References Contact Details',
 'Three References Names and Contact Details',
 'Three Years of Teaching Evaluations',
 'Three confidential letters of recommendation',
 'Three letters of recommendation',
 'Three letters of reference',
 'Three names of reference',
 'Three names of reference to busref@aucegypt.edu with the subject line BUS/Econ/2027',
 'Three names of reference to busref@aucegypt.edu with the subject line BUS/MacroEcon/2027',
 'Three supervisory professional references, including name, address, title, telephone number, and email address',
 'Three to Five references with contact information',
 'Three to five references with contact information',
 'Transcript',
 "Transcript from Bachelor's degree",
 'Transcript of Grades',
 'Transcripts',
 'Transcripts of all graduate degrees',
 'Two Confidential Letters of Recommendation (including one addressing inclusive academic environments and diverse perspectives)',
 'Two Letters of Recommendation',
 'Two course descriptions for upper level undergraduate seminars (approx 150 words each)',
 'Two letters of recommendation',
 'Two-Pager Research Statement',
 'Two-Pager Teaching Philosophy Statement',
 'Unofficial Graduate Transcripts',
 'Unofficial Transcript 1',
 'Unofficial Transcripts',
 'Unofficial Transcripts (Official Transcripts and Official International Course-by-Course Evaluations Due Upon Hire)',
 'Unofficial graduate transcripts',
 'Unofficial transcripts',
 'Up to 3 Most Significant Research Publications',
 'Vita',
 'Writing Sample',
 'Writing Sample (article-length, addressing Moral and Political Economy)',
 'Writing Sample 1',
 'Writing Sample or Job Market Paper',
 'Writing sample of solo-authored work (max 10,000 words)',
 'Written Sample of Scholarly Work',
 'Your job market paper',
 'a sample of recent scholarship',
 'an example of recent research',
 'cover letter',
 'curriculum vitae',
 'evidence of teaching effectiveness',
 'evidence of teaching experience and effectiveness',
 'institutional excellence statement',
 'letter of interest',
 'research plans',
 'sample research paper',
 'statement of teaching interests',
 'statement of teaching interests/philosophy',
 'teaching philosophy',
 'three confidential letters of recommendation',
 'three letters of recommendation',
 'three reference letters',
 'two letters of recommendation'}

In [25]:
merged2['status'] = 'Open'

,file,text,link,date_posted,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,idx,documents
0,data/html_cache/hedj/205.html,Assistant Professor of Economics\n============...,https://marylandconnect.wd1.myworkdayjobs.com/...,2026-07-22 17:45:52.497,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"['Undergraduate Teaching', 'Research', 'Public...",['Evidence of teaching effectiveness at the un...,"['Ph.D. in Economics', 'Demonstrated potential...",Not eligible,0,"[Curriculum Vitae, Cover Letter, Job Market Pa..."
1,data/html_cache/hedj/74.html,"Postdoctoral Fellow in Economic Science, Fall ...",https://apply.interfolio.com/194065,2026-09-25 17:35:19.32,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"['Design, program and run experiments using hu...",[],"['PhD in Economics, any field, with an emphasi...",Not eligible,1,"[Statement of interest, CV, Job Market Paper, ..."
2,data/html_cache/hedj/23.html,Visiting Assistant Professor of Global Studies...,https://apply.interfolio.com/195065,2026-10-08 11:32:45.427,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"['Teaching', 'Research', 'Service']","['Experience in critical political economy', '...",['Strong teaching excellence'],Not eligible,2,"[Resume, Cover Letter, Curriculum Vitae, State..."
3,data/html_cache/hedj/194.html,Lecturer in Public and International Affairs\n...,https://www.click2apply.net/kNe4BNFDn2X4OHE6c2QNR,2026-08-06 13:26:41.55,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,NaN,"['Undergraduate Teaching', 'Co-teaching in are...",[],['Advanced degree or comparable experience in ...,Not eligible,3,"[Curriculum Vitae, Cover Letter, Teaching Stat..."
4,data/html_cache/hedj/244.html,HKU Professoriate Recruitment (Business and Ec...,https://secure.dc5.pageuppeople.com/apply/932/...,2020-11-06 12:00:11.74,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",NaN,NaN,"['Undergraduate Teaching', 'Research', 'Public...",['Experience with relevant technologies and me...,"['Research in emerging academic disciplines', ...",Is eligible for H1B visa sponsorship,4,"[Resume, Cover Letter, Research Statement, Tea..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,data/html_cache/hedj/139.html,Assistant Professor (Tenure Track) - Economics...,https://apply.interfolio.com/188852,2026-09-05 18:17:26.873,Assistant Professor (Tenure Track) - Economics,DePaul University,"Chicago, IL",2027-07-01,2027-09-11,"[""Teach undergraduate and graduate courses in ...",[],['Ph.D. in Economics or closely related field ...,Not Mentioned,240,"[Cover Letter, C.V., Research Statement, Teach..."
241,data/html_cache/hedj/142.html,Lecturer or Senior Lecturer in Economics\n====...,https://ukjobs.uky.edu/postings/647459,2026-09-04 08:54:25.533,Lecturer or Senior Lecturer in Economics,University of Kentucky,"Lexington, KY",2027-08-01,2027-08-01,"['Teaching in large-lecture sections', ""Teachi...",['Experience with teaching large lecture forma...,"['Ph. D. in Economics', 'Prior college/univers...",Not Mentioned,241,"[Cover Letter, CV, Statement of Teaching Philo..."
242,data/html_cache/hedj/115.html,SNF Agora Academy Postdoctoral Fellowship - 20...,https://apply.interfolio.com/193231,2026-09-15 21:16:25.827,SNF Agora Institute - Postdoctoral Fellowship,Johns Hopkins University,"Baltimore, MD",NaN,Open Until Filled,"['carry out their own research', 'participate ...","['strong academic record', 'trajectory to cont...","['doctorate in May 2025 or later', 'engage wit...",Not Mentioned,242,"[CV, Research statement (max 1,500 words), Wri..."
243,data/html_cache/hedj/103.html,TTU Post Doctoral Research Associate\n========...,https://apptrkr.com/9837874,2026-09-18 11:34:18.287,TTU Post Doctoral Research Associate,Texas Tech University,"Lubbock, TX",Not mentioned,Not mentioned,['Performs specialized Post Doctoral work in t...,['Demonstrated track record of published resea...,"['PhD in area of project specialization', 'Kno...",Not Mentioned,243,"[Resume, Cover Letter]"
244,data/html_cache/hedj/154.html,Peter B. Kenen Visiting Fellowship\n==========...,https://www.click2apply.net/wJedg5sDOwVpBTa5Tg4ja,2026-09-01 12:23:53.517,Peter B. Kenen Visiting Fellowship,Princeton University,"Princeton, NJ",Not specified in the text,Not specified in the text,['Pursue research on any topic in internationa...,['Current Ph.D. economist'],['Must hold a full-time position in a universi...,Not eligible for visa sponsorship,244,"[Resume, Cover Letter]"

In [4]:
import glob
import pandas as pd
import re
from bs4 import BeautifulSoup
from urllib.parse import urlparse, parse_qs

In [2]:
files = glob.glob("data/html_cache/hedj/*.html")

In [18]:
ids = []
mappings = {}
for file in files:
    with open(file, "r", encoding="utf-8") as f:
        html_content = f.read()
    soup = BeautifulSoup(html_content, "lxml")

    # inputs = soup.find_all('input', {'data-jobcode': True})
    spans = soup.find_all('span', {'data-jc': True}, recursive=True)

    # 2. Extract the JobCode from each link
    print(f"File: {file}")
    if spans:
        id = spans[0]['data-jc']
        print(id)
        ids.append(id)
        mappings[file] = id

File: data/html_cache/hedj/205.html
179507024
File: data/html_cache/hedj/74.html
179568871
File: data/html_cache/hedj/23.html
179582487
File: data/html_cache/hedj/194.html
179521072
File: data/html_cache/hedj/244.html
177351010
File: data/html_cache/hedj/35.html
179580324
File: data/html_cache/hedj/182.html
179532598
File: data/html_cache/hedj/213.html
179488833
File: data/html_cache/hedj/62.html
179572493
File: data/html_cache/hedj/9.html
179587474
File: data/html_cache/hedj/141.html
179548005
File: data/html_cache/hedj/19.html
179583833
File: data/html_cache/hedj/116.html
179557582
File: data/html_cache/hedj/229.html
179316650
File: data/html_cache/hedj/100.html
179561688
File: data/html_cache/hedj/58.html
179574139
File: data/html_cache/hedj/157.html
179543480
File: data/html_cache/hedj/120.html
179556511
File: data/html_cache/hedj/78.html
179567015
File: data/html_cache/hedj/97.html
179562585
File: data/html_cache/hedj/209.html
179501121
File: data/html_cache/hedj/177.html
179534691
File: data/html_cache/hedj/198.html
179517309
File: data/html_cache/hedj/161.html
179543373
File: data/html_cache/hedj/39.html
179579046
File: data/html_cache/hedj/136.html
179551726
File: data/html_cache/hedj/81.html
179566576
File: data/html_cache/hedj/5.html
179588531
File: data/html_cache/hedj/15.html
179586259
File: data/html_cache/hedj/42.html
179578770
File: data/html_cache/hedj/233.html
179309097
File: data/html_cache/hedj/54.html
179575164
File: data/html_cache/hedj/225.html
179344725
File: data/html_cache/hedj/224.html
179355805
File: data/html_cache/hedj/55.html
179575126
File: data/html_cache/hedj/232.html
179316579
File: data/html_cache/hedj/43.html
179578644
File: data/html_cache/hedj/14.html
179586765
File: data/html_cache/hedj/137.html
179549119
File: data/html_cache/hedj/4.html
179588620
File: data/html_cache/hedj/80.html
179566808
File: data/html_cache/hedj/160.html
179543374
File: data/html_cache/hedj/38.html
179579237
File: data/html_cache/hedj/176.html
179534785
File: data/html_cache/hedj/199.html
179513962
File: data/html_cache/hedj/208.html
179503872
File: data/html_cache/hedj/121.html
179556194
File: data/html_cache/hedj/79.html
179566930
File: data/html_cache/hedj/96.html
179562619
File: data/html_cache/hedj/156.html
179543621
File: data/html_cache/hedj/101.html
179561685
File: data/html_cache/hedj/59.html
179573614
File: data/html_cache/hedj/228.html
179328037
File: data/html_cache/hedj/117.html
179557395
File: data/html_cache/hedj/140.html
179548610
File: data/html_cache/hedj/18.html
179584121
File: data/html_cache/hedj/63.html
179572360
File: data/html_cache/hedj/8.html
179587521
File: data/html_cache/hedj/212.html
179498044
File: data/html_cache/hedj/34.html
179580440
File: data/html_cache/hedj/183.html
179531348
File: data/html_cache/hedj/22.html
179582640
File: data/html_cache/hedj/195.html
179518762
File: data/html_cache/hedj/75.html
179568436
File: data/html_cache/hedj/204.html
179507065
File: data/html_cache/hedj/126.html
179555002
File: data/html_cache/hedj/91.html
179563011
File: data/html_cache/hedj/171.html
179539046
File: data/html_cache/hedj/29.html
179581871
File: data/html_cache/hedj/167.html
179539683
File: data/html_cache/hedj/188.html
179526294
File: data/html_cache/hedj/130.html
179553172
File: data/html_cache/hedj/68.html
179571077
File: data/html_cache/hedj/87.html
179563922
File: data/html_cache/hedj/3.html
179589055
File: data/html_cache/hedj/219.html
179441412
File: data/html_cache/hedj/13.html
179586868
File: data/html_cache/hedj/44.html
179578088
File: data/html_cache/hedj/235.html
179282612
File: data/html_cache/hedj/52.html
179575899
File: data/html_cache/hedj/223.html
179400544
File: data/html_cache/hedj/203.html
179509006
File: data/html_cache/hedj/72.html
179569299
File: data/html_cache/hedj/25.html
179581990
File: data/html_cache/hedj/192.html
179521391
File: data/html_cache/hedj/242.html
178609162
File: data/html_cache/hedj/33.html
179580513
File: data/html_cache/hedj/184.html
179531333
File: data/html_cache/hedj/215.html
179460088
File: data/html_cache/hedj/64.html
179572197
File: data/html_cache/hedj/147.html
179545313
File: data/html_cache/hedj/239.html
179194071
File: data/html_cache/hedj/110.html
179559233
File: data/html_cache/hedj/48.html
179576257
File: data/html_cache/hedj/106.html
179560727
File: data/html_cache/hedj/151.html
179544927
File: data/html_cache/hedj/150.html
179544928
File: data/html_cache/hedj/107.html
179560001
File: data/html_cache/hedj/111.html
179558882
File: data/html_cache/hedj/49.html
179576208
File: data/html_cache/hedj/238.html
179251847
File: data/html_cache/hedj/146.html
179545473
File: data/html_cache/hedj/65.html
179571809
File: data/html_cache/hedj/214.html
179470679
File: data/html_cache/hedj/32.html
179580663
File: data/html_cache/hedj/185.html
179529938
File: data/html_cache/hedj/243.html
178399962
File: data/html_cache/hedj/24.html
179582060
File: data/html_cache/hedj/193.html
179521382
File: data/html_cache/hedj/73.html
179569026
File: data/html_cache/hedj/202.html
179510638
File: data/html_cache/hedj/222.html
179404525
File: data/html_cache/hedj/53.html
179575179
File: data/html_cache/hedj/234.html
179288428
File: data/html_cache/hedj/45.html
179577704
File: data/html_cache/hedj/12.html
179587031
File: data/html_cache/hedj/218.html
179443015
File: data/html_cache/hedj/131.html
179553136
File: data/html_cache/hedj/69.html
179569584
File: data/html_cache/hedj/2.html
179589155
File: data/html_cache/hedj/86.html
179563923
File: data/html_cache/hedj/166.html
179540736
File: data/html_cache/hedj/189.html
179526097
File: data/html_cache/hedj/170.html
179539415
File: data/html_cache/hedj/28.html
179581878
File: data/html_cache/hedj/127.html
179553998
File: data/html_cache/hedj/90.html
179563330
File: data/html_cache/hedj/221.html
179416607
File: data/html_cache/hedj/50.html
179576136
File: data/html_cache/hedj/108.html
179559446
File: data/html_cache/hedj/237.html
179261659
File: data/html_cache/hedj/46.html
179577421
File: data/html_cache/hedj/11.html
179587176
File: data/html_cache/hedj/149.html
179545065
File: data/html_cache/hedj/1.html
179589284
File: data/html_cache/hedj/85.html
179564407
File: data/html_cache/hedj/132.html
179553089
File: data/html_cache/hedj/165.html
179541612
File: data/html_cache/hedj/173.html
179536428
File: data/html_cache/hedj/93.html
179562966
File: data/html_cache/hedj/124.html
179556109
File: data/html_cache/hedj/153.html
179544507
File: data/html_cache/hedj/104.html
179561567
File: data/html_cache/hedj/112.html
179558577
File: data/html_cache/hedj/145.html
179545630
File: data/html_cache/hedj/89.html
179563417
File: data/html_cache/hedj/66.html
179571282
File: data/html_cache/hedj/217.html
179453283
File: data/html_cache/hedj/186.html
179529629
File: data/html_cache/hedj/31.html
179581380
File: data/html_cache/hedj/169.html
179539431
File: data/html_cache/hedj/240.html
179113696
File: data/html_cache/hedj/190.html
179525402
File: data/html_cache/hedj/27.html
179581901
File: data/html_cache/hedj/70.html
179568836
File: data/html_cache/hedj/128.html
179553384
File: data/html_cache/hedj/201.html
179511990
File: data/html_cache/hedj/200.html
179512171
File: data/html_cache/hedj/71.html
179569413
File: data/html_cache/hedj/129.html
179553225
File: data/html_cache/hedj/191.html
179524514
File: data/html_cache/hedj/26.html
179581929
File: data/html_cache/hedj/241.html
179083126
File: data/html_cache/hedj/187.html
179526606
File: data/html_cache/hedj/30.html
179581708
File: data/html_cache/hedj/168.html
179539682
File: data/html_cache/hedj/216.html
179454585
File: data/html_cache/hedj/88.html
179563648
File: data/html_cache/hedj/67.html
179571255
File: data/html_cache/hedj/144.html
179545808
File: data/html_cache/hedj/113.html
179558201
File: data/html_cache/hedj/105.html
179561439
File: data/html_cache/hedj/152.html
179544887
File: data/html_cache/hedj/92.html
179562967
File: data/html_cache/hedj/125.html
179555412
File: data/html_cache/hedj/172.html
179538252
File: data/html_cache/hedj/164.html
179541882
File: data/html_cache/hedj/84.html
179565325
File: data/html_cache/hedj/0.html
179579207
File: data/html_cache/hedj/133.html
File: data/html_cache/hedj/10.html
179587271
File: data/html_cache/hedj/148.html
179545181
File: data/html_cache/hedj/47.html
179577219
File: data/html_cache/hedj/236.html
179262513
File: data/html_cache/hedj/51.html
179576135
File: data/html_cache/hedj/109.html
179559234
File: data/html_cache/hedj/220.html
179437499
File: data/html_cache/hedj/155.html
179544029
File: data/html_cache/hedj/102.html
179561642
File: data/html_cache/hedj/114.html
179558200
File: data/html_cache/hedj/143.html
179545935
File: data/html_cache/hedj/60.html
179573613
File: data/html_cache/hedj/138.html
179549050
File: data/html_cache/hedj/211.html
179498357
File: data/html_cache/hedj/180.html
179533782
File: data/html_cache/hedj/37.html
179579846
File: data/html_cache/hedj/196.html
179518482
File: data/html_cache/hedj/21.html
179583057
File: data/html_cache/hedj/179.html
179533789
File: data/html_cache/hedj/99.html
179562309
File: data/html_cache/hedj/76.html
179568126
File: data/html_cache/hedj/207.html
179504671
File: data/html_cache/hedj/159.html
179543375
File: data/html_cache/hedj/227.html
179329945
File: data/html_cache/hedj/56.html
179575125
File: data/html_cache/hedj/231.html
179316581
File: data/html_cache/hedj/40.html
179578875
File: data/html_cache/hedj/118.html
179557165
File: data/html_cache/hedj/17.html
179584327
File: data/html_cache/hedj/7.html
179587606
File: data/html_cache/hedj/83.html
179566496
File: data/html_cache/hedj/134.html
179551728
File: data/html_cache/hedj/163.html
179542482
File: data/html_cache/hedj/175.html
179534786
File: data/html_cache/hedj/95.html
179562753
File: data/html_cache/hedj/122.html
179556176
File: data/html_cache/hedj/94.html
179562754
File: data/html_cache/hedj/123.html
179556152
File: data/html_cache/hedj/174.html
179534798
File: data/html_cache/hedj/162.html
179542744
File: data/html_cache/hedj/82.html
179566556
File: data/html_cache/hedj/6.html
179588048
File: data/html_cache/hedj/135.html
179551727
File: data/html_cache/hedj/16.html
179584824
File: data/html_cache/hedj/41.html
179578855
File: data/html_cache/hedj/119.html
179557164
File: data/html_cache/hedj/230.html
179316585
File: data/html_cache/hedj/57.html
179575074
File: data/html_cache/hedj/226.html
179337233
File: data/html_cache/hedj/158.html
179543474
File: data/html_cache/hedj/206.html
179504673
File: data/html_cache/hedj/98.html
179562581
File: data/html_cache/hedj/77.html
179567314
File: data/html_cache/hedj/197.html
179517947
File: data/html_cache/hedj/20.html
179583465
File: data/html_cache/hedj/178.html
179534287
File: data/html_cache/hedj/181.html
179533634
File: data/html_cache/hedj/36.html
179579901
File: data/html_cache/hedj/210.html
179498358
File: data/html_cache/hedj/61.html
179572963
File: data/html_cache/hedj/139.html
179548639
File: data/html_cache/hedj/142.html
179547688
File: data/html_cache/hedj/115.html
179557793
File: data/html_cache/hedj/103.html
179561620
File: data/html_cache/hedj/154.html
179544157

In [19]:
uniqids = set(ids)
print(len(uniqids), len(ids))

244 244

In [20]:
print(len(mappings), len(files))

244 245

In [22]:
from pathlib import Path

for file, id in mappings.items():
    print(f"{file} --> data/html_cache/hedj/{id}.html")
    # # Define the file paths
    # old_file = Path("documents/old_name.txt")
    # new_file = old_file.with_name("new_name.txt")
    #
    # # Rename the file
    # old_file.rename(new_file)

data/html_cache/hedj/205.html --> data/html_cache/hedj/179507024.html
data/html_cache/hedj/74.html --> data/html_cache/hedj/179568871.html
data/html_cache/hedj/23.html --> data/html_cache/hedj/179582487.html
data/html_cache/hedj/194.html --> data/html_cache/hedj/179521072.html
data/html_cache/hedj/244.html --> data/html_cache/hedj/177351010.html
data/html_cache/hedj/35.html --> data/html_cache/hedj/179580324.html
data/html_cache/hedj/182.html --> data/html_cache/hedj/179532598.html
data/html_cache/hedj/213.html --> data/html_cache/hedj/179488833.html
data/html_cache/hedj/62.html --> data/html_cache/hedj/179572493.html
data/html_cache/hedj/9.html --> data/html_cache/hedj/179587474.html
data/html_cache/hedj/141.html --> data/html_cache/hedj/179548005.html
data/html_cache/hedj/19.html --> data/html_cache/hedj/179583833.html
data/html_cache/hedj/116.html --> data/html_cache/hedj/179557582.html
data/html_cache/hedj/229.html --> data/html_cache/hedj/179316650.html
data/html_cache/hedj/100.html --> data/html_cache/hedj/179561688.html
data/html_cache/hedj/58.html --> data/html_cache/hedj/179574139.html
data/html_cache/hedj/157.html --> data/html_cache/hedj/179543480.html
data/html_cache/hedj/120.html --> data/html_cache/hedj/179556511.html
data/html_cache/hedj/78.html --> data/html_cache/hedj/179567015.html
data/html_cache/hedj/97.html --> data/html_cache/hedj/179562585.html
data/html_cache/hedj/209.html --> data/html_cache/hedj/179501121.html
data/html_cache/hedj/177.html --> data/html_cache/hedj/179534691.html
data/html_cache/hedj/198.html --> data/html_cache/hedj/179517309.html
data/html_cache/hedj/161.html --> data/html_cache/hedj/179543373.html
data/html_cache/hedj/39.html --> data/html_cache/hedj/179579046.html
data/html_cache/hedj/136.html --> data/html_cache/hedj/179551726.html
data/html_cache/hedj/81.html --> data/html_cache/hedj/179566576.html
data/html_cache/hedj/5.html --> data/html_cache/hedj/179588531.html
data/html_cache/hedj/15.html --> data/html_cache/hedj/179586259.html
data/html_cache/hedj/42.html --> data/html_cache/hedj/179578770.html
data/html_cache/hedj/233.html --> data/html_cache/hedj/179309097.html
data/html_cache/hedj/54.html --> data/html_cache/hedj/179575164.html
data/html_cache/hedj/225.html --> data/html_cache/hedj/179344725.html
data/html_cache/hedj/224.html --> data/html_cache/hedj/179355805.html
data/html_cache/hedj/55.html --> data/html_cache/hedj/179575126.html
data/html_cache/hedj/232.html --> data/html_cache/hedj/179316579.html
data/html_cache/hedj/43.html --> data/html_cache/hedj/179578644.html
data/html_cache/hedj/14.html --> data/html_cache/hedj/179586765.html
data/html_cache/hedj/137.html --> data/html_cache/hedj/179549119.html
data/html_cache/hedj/4.html --> data/html_cache/hedj/179588620.html
data/html_cache/hedj/80.html --> data/html_cache/hedj/179566808.html
data/html_cache/hedj/160.html --> data/html_cache/hedj/179543374.html
data/html_cache/hedj/38.html --> data/html_cache/hedj/179579237.html
data/html_cache/hedj/176.html --> data/html_cache/hedj/179534785.html
data/html_cache/hedj/199.html --> data/html_cache/hedj/179513962.html
data/html_cache/hedj/208.html --> data/html_cache/hedj/179503872.html
data/html_cache/hedj/121.html --> data/html_cache/hedj/179556194.html
data/html_cache/hedj/79.html --> data/html_cache/hedj/179566930.html
data/html_cache/hedj/96.html --> data/html_cache/hedj/179562619.html
data/html_cache/hedj/156.html --> data/html_cache/hedj/179543621.html
data/html_cache/hedj/101.html --> data/html_cache/hedj/179561685.html
data/html_cache/hedj/59.html --> data/html_cache/hedj/179573614.html
data/html_cache/hedj/228.html --> data/html_cache/hedj/179328037.html
data/html_cache/hedj/117.html --> data/html_cache/hedj/179557395.html
data/html_cache/hedj/140.html --> data/html_cache/hedj/179548610.html
data/html_cache/hedj/18.html --> data/html_cache/hedj/179584121.html
data/html_cache/hedj/63.html --> data/html_cache/hedj/179572360.html
data/html_cache/hedj/8.html --> data/html_cache/hedj/179587521.html
data/html_cache/hedj/212.html --> data/html_cache/hedj/179498044.html
data/html_cache/hedj/34.html --> data/html_cache/hedj/179580440.html
data/html_cache/hedj/183.html --> data/html_cache/hedj/179531348.html
data/html_cache/hedj/22.html --> data/html_cache/hedj/179582640.html
data/html_cache/hedj/195.html --> data/html_cache/hedj/179518762.html
data/html_cache/hedj/75.html --> data/html_cache/hedj/179568436.html
data/html_cache/hedj/204.html --> data/html_cache/hedj/179507065.html
data/html_cache/hedj/126.html --> data/html_cache/hedj/179555002.html
data/html_cache/hedj/91.html --> data/html_cache/hedj/179563011.html
data/html_cache/hedj/171.html --> data/html_cache/hedj/179539046.html
data/html_cache/hedj/29.html --> data/html_cache/hedj/179581871.html
data/html_cache/hedj/167.html --> data/html_cache/hedj/179539683.html
data/html_cache/hedj/188.html --> data/html_cache/hedj/179526294.html
data/html_cache/hedj/130.html --> data/html_cache/hedj/179553172.html
data/html_cache/hedj/68.html --> data/html_cache/hedj/179571077.html
data/html_cache/hedj/87.html --> data/html_cache/hedj/179563922.html
data/html_cache/hedj/3.html --> data/html_cache/hedj/179589055.html
data/html_cache/hedj/219.html --> data/html_cache/hedj/179441412.html
data/html_cache/hedj/13.html --> data/html_cache/hedj/179586868.html
data/html_cache/hedj/44.html --> data/html_cache/hedj/179578088.html
data/html_cache/hedj/235.html --> data/html_cache/hedj/179282612.html
data/html_cache/hedj/52.html --> data/html_cache/hedj/179575899.html
data/html_cache/hedj/223.html --> data/html_cache/hedj/179400544.html
data/html_cache/hedj/203.html --> data/html_cache/hedj/179509006.html
data/html_cache/hedj/72.html --> data/html_cache/hedj/179569299.html
data/html_cache/hedj/25.html --> data/html_cache/hedj/179581990.html
data/html_cache/hedj/192.html --> data/html_cache/hedj/179521391.html
data/html_cache/hedj/242.html --> data/html_cache/hedj/178609162.html
data/html_cache/hedj/33.html --> data/html_cache/hedj/179580513.html
data/html_cache/hedj/184.html --> data/html_cache/hedj/179531333.html
data/html_cache/hedj/215.html --> data/html_cache/hedj/179460088.html
data/html_cache/hedj/64.html --> data/html_cache/hedj/179572197.html
data/html_cache/hedj/147.html --> data/html_cache/hedj/179545313.html
data/html_cache/hedj/239.html --> data/html_cache/hedj/179194071.html
data/html_cache/hedj/110.html --> data/html_cache/hedj/179559233.html
data/html_cache/hedj/48.html --> data/html_cache/hedj/179576257.html
data/html_cache/hedj/106.html --> data/html_cache/hedj/179560727.html
data/html_cache/hedj/151.html --> data/html_cache/hedj/179544927.html
data/html_cache/hedj/150.html --> data/html_cache/hedj/179544928.html
data/html_cache/hedj/107.html --> data/html_cache/hedj/179560001.html
data/html_cache/hedj/111.html --> data/html_cache/hedj/179558882.html
data/html_cache/hedj/49.html --> data/html_cache/hedj/179576208.html
data/html_cache/hedj/238.html --> data/html_cache/hedj/179251847.html
data/html_cache/hedj/146.html --> data/html_cache/hedj/179545473.html
data/html_cache/hedj/65.html --> data/html_cache/hedj/179571809.html
data/html_cache/hedj/214.html --> data/html_cache/hedj/179470679.html
data/html_cache/hedj/32.html --> data/html_cache/hedj/179580663.html
data/html_cache/hedj/185.html --> data/html_cache/hedj/179529938.html
data/html_cache/hedj/243.html --> data/html_cache/hedj/178399962.html
data/html_cache/hedj/24.html --> data/html_cache/hedj/179582060.html
data/html_cache/hedj/193.html --> data/html_cache/hedj/179521382.html
data/html_cache/hedj/73.html --> data/html_cache/hedj/179569026.html
data/html_cache/hedj/202.html --> data/html_cache/hedj/179510638.html
data/html_cache/hedj/222.html --> data/html_cache/hedj/179404525.html
data/html_cache/hedj/53.html --> data/html_cache/hedj/179575179.html
data/html_cache/hedj/234.html --> data/html_cache/hedj/179288428.html
data/html_cache/hedj/45.html --> data/html_cache/hedj/179577704.html
data/html_cache/hedj/12.html --> data/html_cache/hedj/179587031.html
data/html_cache/hedj/218.html --> data/html_cache/hedj/179443015.html
data/html_cache/hedj/131.html --> data/html_cache/hedj/179553136.html
data/html_cache/hedj/69.html --> data/html_cache/hedj/179569584.html
data/html_cache/hedj/2.html --> data/html_cache/hedj/179589155.html
data/html_cache/hedj/86.html --> data/html_cache/hedj/179563923.html
data/html_cache/hedj/166.html --> data/html_cache/hedj/179540736.html
data/html_cache/hedj/189.html --> data/html_cache/hedj/179526097.html
data/html_cache/hedj/170.html --> data/html_cache/hedj/179539415.html
data/html_cache/hedj/28.html --> data/html_cache/hedj/179581878.html
data/html_cache/hedj/127.html --> data/html_cache/hedj/179553998.html
data/html_cache/hedj/90.html --> data/html_cache/hedj/179563330.html
data/html_cache/hedj/221.html --> data/html_cache/hedj/179416607.html
data/html_cache/hedj/50.html --> data/html_cache/hedj/179576136.html
data/html_cache/hedj/108.html --> data/html_cache/hedj/179559446.html
data/html_cache/hedj/237.html --> data/html_cache/hedj/179261659.html
data/html_cache/hedj/46.html --> data/html_cache/hedj/179577421.html
data/html_cache/hedj/11.html --> data/html_cache/hedj/179587176.html
data/html_cache/hedj/149.html --> data/html_cache/hedj/179545065.html
data/html_cache/hedj/1.html --> data/html_cache/hedj/179589284.html
data/html_cache/hedj/85.html --> data/html_cache/hedj/179564407.html
data/html_cache/hedj/132.html --> data/html_cache/hedj/179553089.html
data/html_cache/hedj/165.html --> data/html_cache/hedj/179541612.html
data/html_cache/hedj/173.html --> data/html_cache/hedj/179536428.html
data/html_cache/hedj/93.html --> data/html_cache/hedj/179562966.html
data/html_cache/hedj/124.html --> data/html_cache/hedj/179556109.html
data/html_cache/hedj/153.html --> data/html_cache/hedj/179544507.html
data/html_cache/hedj/104.html --> data/html_cache/hedj/179561567.html
data/html_cache/hedj/112.html --> data/html_cache/hedj/179558577.html
data/html_cache/hedj/145.html --> data/html_cache/hedj/179545630.html
data/html_cache/hedj/89.html --> data/html_cache/hedj/179563417.html
data/html_cache/hedj/66.html --> data/html_cache/hedj/179571282.html
data/html_cache/hedj/217.html --> data/html_cache/hedj/179453283.html
data/html_cache/hedj/186.html --> data/html_cache/hedj/179529629.html
data/html_cache/hedj/31.html --> data/html_cache/hedj/179581380.html
data/html_cache/hedj/169.html --> data/html_cache/hedj/179539431.html
data/html_cache/hedj/240.html --> data/html_cache/hedj/179113696.html
data/html_cache/hedj/190.html --> data/html_cache/hedj/179525402.html
data/html_cache/hedj/27.html --> data/html_cache/hedj/179581901.html
data/html_cache/hedj/70.html --> data/html_cache/hedj/179568836.html
data/html_cache/hedj/128.html --> data/html_cache/hedj/179553384.html
data/html_cache/hedj/201.html --> data/html_cache/hedj/179511990.html
data/html_cache/hedj/200.html --> data/html_cache/hedj/179512171.html
data/html_cache/hedj/71.html --> data/html_cache/hedj/179569413.html
data/html_cache/hedj/129.html --> data/html_cache/hedj/179553225.html
data/html_cache/hedj/191.html --> data/html_cache/hedj/179524514.html
data/html_cache/hedj/26.html --> data/html_cache/hedj/179581929.html
data/html_cache/hedj/241.html --> data/html_cache/hedj/179083126.html
data/html_cache/hedj/187.html --> data/html_cache/hedj/179526606.html
data/html_cache/hedj/30.html --> data/html_cache/hedj/179581708.html
data/html_cache/hedj/168.html --> data/html_cache/hedj/179539682.html
data/html_cache/hedj/216.html --> data/html_cache/hedj/179454585.html
data/html_cache/hedj/88.html --> data/html_cache/hedj/179563648.html
data/html_cache/hedj/67.html --> data/html_cache/hedj/179571255.html
data/html_cache/hedj/144.html --> data/html_cache/hedj/179545808.html
data/html_cache/hedj/113.html --> data/html_cache/hedj/179558201.html
data/html_cache/hedj/105.html --> data/html_cache/hedj/179561439.html
data/html_cache/hedj/152.html --> data/html_cache/hedj/179544887.html
data/html_cache/hedj/92.html --> data/html_cache/hedj/179562967.html
data/html_cache/hedj/125.html --> data/html_cache/hedj/179555412.html
data/html_cache/hedj/172.html --> data/html_cache/hedj/179538252.html
data/html_cache/hedj/164.html --> data/html_cache/hedj/179541882.html
data/html_cache/hedj/84.html --> data/html_cache/hedj/179565325.html
data/html_cache/hedj/0.html --> data/html_cache/hedj/179579207.html
data/html_cache/hedj/10.html --> data/html_cache/hedj/179587271.html
data/html_cache/hedj/148.html --> data/html_cache/hedj/179545181.html
data/html_cache/hedj/47.html --> data/html_cache/hedj/179577219.html
data/html_cache/hedj/236.html --> data/html_cache/hedj/179262513.html
data/html_cache/hedj/51.html --> data/html_cache/hedj/179576135.html
data/html_cache/hedj/109.html --> data/html_cache/hedj/179559234.html
data/html_cache/hedj/220.html --> data/html_cache/hedj/179437499.html
data/html_cache/hedj/155.html --> data/html_cache/hedj/179544029.html
data/html_cache/hedj/102.html --> data/html_cache/hedj/179561642.html
data/html_cache/hedj/114.html --> data/html_cache/hedj/179558200.html
data/html_cache/hedj/143.html --> data/html_cache/hedj/179545935.html
data/html_cache/hedj/60.html --> data/html_cache/hedj/179573613.html
data/html_cache/hedj/138.html --> data/html_cache/hedj/179549050.html
data/html_cache/hedj/211.html --> data/html_cache/hedj/179498357.html
data/html_cache/hedj/180.html --> data/html_cache/hedj/179533782.html
data/html_cache/hedj/37.html --> data/html_cache/hedj/179579846.html
data/html_cache/hedj/196.html --> data/html_cache/hedj/179518482.html
data/html_cache/hedj/21.html --> data/html_cache/hedj/179583057.html
data/html_cache/hedj/179.html --> data/html_cache/hedj/179533789.html
data/html_cache/hedj/99.html --> data/html_cache/hedj/179562309.html
data/html_cache/hedj/76.html --> data/html_cache/hedj/179568126.html
data/html_cache/hedj/207.html --> data/html_cache/hedj/179504671.html
data/html_cache/hedj/159.html --> data/html_cache/hedj/179543375.html
data/html_cache/hedj/227.html --> data/html_cache/hedj/179329945.html
data/html_cache/hedj/56.html --> data/html_cache/hedj/179575125.html
data/html_cache/hedj/231.html --> data/html_cache/hedj/179316581.html
data/html_cache/hedj/40.html --> data/html_cache/hedj/179578875.html
data/html_cache/hedj/118.html --> data/html_cache/hedj/179557165.html
data/html_cache/hedj/17.html --> data/html_cache/hedj/179584327.html
data/html_cache/hedj/7.html --> data/html_cache/hedj/179587606.html
data/html_cache/hedj/83.html --> data/html_cache/hedj/179566496.html
data/html_cache/hedj/134.html --> data/html_cache/hedj/179551728.html
data/html_cache/hedj/163.html --> data/html_cache/hedj/179542482.html
data/html_cache/hedj/175.html --> data/html_cache/hedj/179534786.html
data/html_cache/hedj/95.html --> data/html_cache/hedj/179562753.html
data/html_cache/hedj/122.html --> data/html_cache/hedj/179556176.html
data/html_cache/hedj/94.html --> data/html_cache/hedj/179562754.html
data/html_cache/hedj/123.html --> data/html_cache/hedj/179556152.html
data/html_cache/hedj/174.html --> data/html_cache/hedj/179534798.html
data/html_cache/hedj/162.html --> data/html_cache/hedj/179542744.html
data/html_cache/hedj/82.html --> data/html_cache/hedj/179566556.html
data/html_cache/hedj/6.html --> data/html_cache/hedj/179588048.html
data/html_cache/hedj/135.html --> data/html_cache/hedj/179551727.html
data/html_cache/hedj/16.html --> data/html_cache/hedj/179584824.html
data/html_cache/hedj/41.html --> data/html_cache/hedj/179578855.html
data/html_cache/hedj/119.html --> data/html_cache/hedj/179557164.html
data/html_cache/hedj/230.html --> data/html_cache/hedj/179316585.html
data/html_cache/hedj/57.html --> data/html_cache/hedj/179575074.html
data/html_cache/hedj/226.html --> data/html_cache/hedj/179337233.html
data/html_cache/hedj/158.html --> data/html_cache/hedj/179543474.html
data/html_cache/hedj/206.html --> data/html_cache/hedj/179504673.html
data/html_cache/hedj/98.html --> data/html_cache/hedj/179562581.html
data/html_cache/hedj/77.html --> data/html_cache/hedj/179567314.html
data/html_cache/hedj/197.html --> data/html_cache/hedj/179517947.html
data/html_cache/hedj/20.html --> data/html_cache/hedj/179583465.html
data/html_cache/hedj/178.html --> data/html_cache/hedj/179534287.html
data/html_cache/hedj/181.html --> data/html_cache/hedj/179533634.html
data/html_cache/hedj/36.html --> data/html_cache/hedj/179579901.html
data/html_cache/hedj/210.html --> data/html_cache/hedj/179498358.html
data/html_cache/hedj/61.html --> data/html_cache/hedj/179572963.html
data/html_cache/hedj/139.html --> data/html_cache/hedj/179548639.html
data/html_cache/hedj/142.html --> data/html_cache/hedj/179547688.html
data/html_cache/hedj/115.html --> data/html_cache/hedj/179557793.html
data/html_cache/hedj/103.html --> data/html_cache/hedj/179561620.html
data/html_cache/hedj/154.html --> data/html_cache/hedj/179544157.html

In [23]:
df = pd.read_csv("data/hedjobs.csv")

In [26]:
df['file'] = df['file'].replace(mappings)
df

,file,text,link,date_posted,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,idx,documents,status
0,179507024,Assistant Professor of Economics\n============...,https://marylandconnect.wd1.myworkdayjobs.com/...,2026-07-22 17:45:52.497,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"['Undergraduate Teaching', 'Research', 'Public...",['Evidence of teaching effectiveness at the un...,"['Ph.D. in Economics', 'Demonstrated potential...",Not eligible,0,"['Curriculum Vitae', 'Cover Letter', 'Job Mark...",...
1,179568871,"Postdoctoral Fellow in Economic Science, Fall ...",https://apply.interfolio.com/194065,2026-09-25 17:35:19.32,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"['Design, program and run experiments using hu...",[],"['PhD in Economics, any field, with an emphasi...",Not eligible,1,"['Statement of interest', 'CV', 'Job Market Pa...",n
2,179582487,Visiting Assistant Professor of Global Studies...,https://apply.interfolio.com/195065,2026-10-08 11:32:45.427,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"['Teaching', 'Research', 'Service']","['Experience in critical political economy', '...",['Strong teaching excellence'],Not eligible,2,"['Resume', 'Cover Letter', 'Curriculum Vitae',...",n
3,179521072,Lecturer in Public and International Affairs\n...,https://www.click2apply.net/kNe4BNFDn2X4OHE6c2QNR,2026-08-06 13:26:41.55,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,NaN,"['Undergraduate Teaching', 'Co-teaching in are...",[],['Advanced degree or comparable experience in ...,Not eligible,3,"['Curriculum Vitae', 'Cover Letter', 'Teaching...",n
4,177351010,HKU Professoriate Recruitment (Business and Ec...,https://secure.dc5.pageuppeople.com/apply/932/...,2020-11-06 12:00:11.74,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",NaN,NaN,"['Undergraduate Teaching', 'Research', 'Public...",['Experience with relevant technologies and me...,"['Research in emerging academic disciplines', ...",Is eligible for H1B visa sponsorship,4,"['Resume', 'Cover Letter', 'Research Statement...",n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,179548639,Assistant Professor (Tenure Track) - Economics...,https://apply.interfolio.com/188852,2026-09-05 18:17:26.873,Assistant Professor (Tenure Track) - Economics,DePaul University,"Chicago, IL",2027-07-01,2027-09-11,"[""Teach undergraduate and graduate courses in ...",[],['Ph.D. in Economics or closely related field ...,Not Mentioned,240,"['Cover Letter', 'C.V.', 'Research Statement',...",y
241,179547688,Lecturer or Senior Lecturer in Economics\n====...,https://ukjobs.uky.edu/postings/647459,2026-09-04 08:54:25.533,Lecturer or Senior Lecturer in Economics,University of Kentucky,"Lexington, KY",2027-08-01,2027-08-01,"['Teaching in large-lecture sections', ""Teachi...",['Experience with teaching large lecture forma...,"['Ph. D. in Economics', 'Prior college/univers...",Not Mentioned,241,"['Cover Letter', 'CV', 'Statement of Teaching ...",m
242,179557793,SNF Agora Academy Postdoctoral Fellowship - 20...,https://apply.interfolio.com/193231,2026-09-15 21:16:25.827,SNF Agora Institute - Postdoctoral Fellowship,Johns Hopkins University,"Baltimore, MD",NaN,Open Until Filled,"['carry out their own research', 'participate ...","['strong academic record', 'trajectory to cont...","['doctorate in May 2025 or later', 'engage wit...",Not Mentioned,242,"['CV', 'Research statement (max 1,500 words)',...",n
243,179561620,TTU Post Doctoral Research Associate\n========...,https://apptrkr.com/9837874,2026-09-18 11:34:18.287,TTU Post Doctoral Research Associate,Texas Tech University,"Lubbock, TX",Not mentioned,Not mentioned,['Performs specialized Post Doctoral work in t...,['Demonstrated track record of published resea...,"['PhD in area of project specialization', 'Kno...",Not Mentioned,243,"['Resume', 'Cover Letter']",n
244,179544157,Peter B. Kenen Visiting Fellowship\n==========...,https://www.click2apply.net/wJedg5sDOwVpBTa5Tg4ja,2026-09-01 12:23:53.517,Peter B. Kenen Visiting Fellowship,Princeton University,"Princeton, NJ",Not specified in the text,Not specified in the text,['Pursue research on any topic in internationa...,['Current Ph.D. economist'],['Must hold a full-time position in a universi...,Not eligible for visa sponsorship,244,"['Resume', 'Cover Letter']",n

In [27]:
df = df.rename(columns={'file': 'id'})
df

,id,text,link,date_posted,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,idx,documents,status
0,179507024,Assistant Professor of Economics\n============...,https://marylandconnect.wd1.myworkdayjobs.com/...,2026-07-22 17:45:52.497,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"['Undergraduate Teaching', 'Research', 'Public...",['Evidence of teaching effectiveness at the un...,"['Ph.D. in Economics', 'Demonstrated potential...",Not eligible,0,"['Curriculum Vitae', 'Cover Letter', 'Job Mark...",...
1,179568871,"Postdoctoral Fellow in Economic Science, Fall ...",https://apply.interfolio.com/194065,2026-09-25 17:35:19.32,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"['Design, program and run experiments using hu...",[],"['PhD in Economics, any field, with an emphasi...",Not eligible,1,"['Statement of interest', 'CV', 'Job Market Pa...",n
2,179582487,Visiting Assistant Professor of Global Studies...,https://apply.interfolio.com/195065,2026-10-08 11:32:45.427,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"['Teaching', 'Research', 'Service']","['Experience in critical political economy', '...",['Strong teaching excellence'],Not eligible,2,"['Resume', 'Cover Letter', 'Curriculum Vitae',...",n
3,179521072,Lecturer in Public and International Affairs\n...,https://www.click2apply.net/kNe4BNFDn2X4OHE6c2QNR,2026-08-06 13:26:41.55,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,NaN,"['Undergraduate Teaching', 'Co-teaching in are...",[],['Advanced degree or comparable experience in ...,Not eligible,3,"['Curriculum Vitae', 'Cover Letter', 'Teaching...",n
4,177351010,HKU Professoriate Recruitment (Business and Ec...,https://secure.dc5.pageuppeople.com/apply/932/...,2020-11-06 12:00:11.74,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",NaN,NaN,"['Undergraduate Teaching', 'Research', 'Public...",['Experience with relevant technologies and me...,"['Research in emerging academic disciplines', ...",Is eligible for H1B visa sponsorship,4,"['Resume', 'Cover Letter', 'Research Statement...",n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,179548639,Assistant Professor (Tenure Track) - Economics...,https://apply.interfolio.com/188852,2026-09-05 18:17:26.873,Assistant Professor (Tenure Track) - Economics,DePaul University,"Chicago, IL",2027-07-01,2027-09-11,"[""Teach undergraduate and graduate courses in ...",[],['Ph.D. in Economics or closely related field ...,Not Mentioned,240,"['Cover Letter', 'C.V.', 'Research Statement',...",y
241,179547688,Lecturer or Senior Lecturer in Economics\n====...,https://ukjobs.uky.edu/postings/647459,2026-09-04 08:54:25.533,Lecturer or Senior Lecturer in Economics,University of Kentucky,"Lexington, KY",2027-08-01,2027-08-01,"['Teaching in large-lecture sections', ""Teachi...",['Experience with teaching large lecture forma...,"['Ph. D. in Economics', 'Prior college/univers...",Not Mentioned,241,"['Cover Letter', 'CV', 'Statement of Teaching ...",m
242,179557793,SNF Agora Academy Postdoctoral Fellowship - 20...,https://apply.interfolio.com/193231,2026-09-15 21:16:25.827,SNF Agora Institute - Postdoctoral Fellowship,Johns Hopkins University,"Baltimore, MD",NaN,Open Until Filled,"['carry out their own research', 'participate ...","['strong academic record', 'trajectory to cont...","['doctorate in May 2025 or later', 'engage wit...",Not Mentioned,242,"['CV', 'Research statement (max 1,500 words)',...",n
243,179561620,TTU Post Doctoral Research Associate\n========...,https://apptrkr.com/9837874,2026-09-18 11:34:18.287,TTU Post Doctoral Research Associate,Texas Tech University,"Lubbock, TX",Not mentioned,Not mentioned,['Performs specialized Post Doctoral work in t...,['Demonstrated track record of published resea...,"['PhD in area of project specialization', 'Kno...",Not Mentioned,243,"['Resume', 'Cover Letter']",n
244,179544157,Peter B. Kenen Visiting Fellowship\n==========...,https://www.click2apply.net/wJedg5sDOwVpBTa5Tg4ja,2026-09-01 12:23:53.517,Peter B. Kenen Visiting Fellowship,Princeton University,"Princeton, NJ",Not specified in the text,Not specified in the text,['Pursue research on any topic in internationa...,['Current Ph.D. economist'],['Must hold a full-time position in a universi...,Not eligible for visa sponsorship,244,"['Resume', 'Cover Letter']",n

In [28]:
df = df.drop(columns=['idx'])
df

,id,text,link,date_posted,job_title,university,location,review_start,deadline,responsibilities,preferred_qualifications,required_skills,visa_sponsorship,documents,status
0,179507024,Assistant Professor of Economics\n============...,https://marylandconnect.wd1.myworkdayjobs.com/...,2026-07-22 17:45:52.497,Assistant Professor of Economics,Salisbury University,"Salisbury, MD",2026-09-11,2026-09-11,"['Undergraduate Teaching', 'Research', 'Public...",['Evidence of teaching effectiveness at the un...,"['Ph.D. in Economics', 'Demonstrated potential...",Not eligible,"['Curriculum Vitae', 'Cover Letter', 'Job Mark...",...
1,179568871,"Postdoctoral Fellow in Economic Science, Fall ...",https://apply.interfolio.com/194065,2026-09-25 17:35:19.32,"Postdoctoral Fellow in Economic Science, Fall ...",Chapman University,"Orange, CA",2027-08-01,2027-08-01,"['Design, program and run experiments using hu...",[],"['PhD in Economics, any field, with an emphasi...",Not eligible,"['Statement of interest', 'CV', 'Job Market Pa...",n
2,179582487,Visiting Assistant Professor of Global Studies...,https://apply.interfolio.com/195065,2026-10-08 11:32:45.427,Visiting Assistant Professor of Global Studies...,Colby College,"Waterville, ME",2026-12-04,2026-12-31,"['Teaching', 'Research', 'Service']","['Experience in critical political economy', '...",['Strong teaching excellence'],Not eligible,"['Resume', 'Cover Letter', 'Curriculum Vitae',...",n
3,179521072,Lecturer in Public and International Affairs\n...,https://www.click2apply.net/kNe4BNFDn2X4OHE6c2QNR,2026-08-06 13:26:41.55,Lecturer in Public and International Affairs,Princeton University,"Princeton, NJ",2026-03-19,NaN,"['Undergraduate Teaching', 'Co-teaching in are...",[],['Advanced degree or comparable experience in ...,Not eligible,"['Curriculum Vitae', 'Cover Letter', 'Teaching...",n
4,177351010,HKU Professoriate Recruitment (Business and Ec...,https://secure.dc5.pageuppeople.com/apply/932/...,2020-11-06 12:00:11.74,"Assistant, Associate, or Full Professor in Eme...",University of Hong Kong (HKU),"Hong Kong, Hong Kong",NaN,NaN,"['Undergraduate Teaching', 'Research', 'Public...",['Experience with relevant technologies and me...,"['Research in emerging academic disciplines', ...",Is eligible for H1B visa sponsorship,"['Resume', 'Cover Letter', 'Research Statement...",n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,179548639,Assistant Professor (Tenure Track) - Economics...,https://apply.interfolio.com/188852,2026-09-05 18:17:26.873,Assistant Professor (Tenure Track) - Economics,DePaul University,"Chicago, IL",2027-07-01,2027-09-11,"[""Teach undergraduate and graduate courses in ...",[],['Ph.D. in Economics or closely related field ...,Not Mentioned,"['Cover Letter', 'C.V.', 'Research Statement',...",y
241,179547688,Lecturer or Senior Lecturer in Economics\n====...,https://ukjobs.uky.edu/postings/647459,2026-09-04 08:54:25.533,Lecturer or Senior Lecturer in Economics,University of Kentucky,"Lexington, KY",2027-08-01,2027-08-01,"['Teaching in large-lecture sections', ""Teachi...",['Experience with teaching large lecture forma...,"['Ph. D. in Economics', 'Prior college/univers...",Not Mentioned,"['Cover Letter', 'CV', 'Statement of Teaching ...",m
242,179557793,SNF Agora Academy Postdoctoral Fellowship - 20...,https://apply.interfolio.com/193231,2026-09-15 21:16:25.827,SNF Agora Institute - Postdoctoral Fellowship,Johns Hopkins University,"Baltimore, MD",NaN,Open Until Filled,"['carry out their own research', 'participate ...","['strong academic record', 'trajectory to cont...","['doctorate in May 2025 or later', 'engage wit...",Not Mentioned,"['CV', 'Research statement (max 1,500 words)',...",n
243,179561620,TTU Post Doctoral Research Associate\n========...,https://apptrkr.com/9837874,2026-09-18 11:34:18.287,TTU Post Doctoral Research Associate,Texas Tech University,"Lubbock, TX",Not mentioned,Not mentioned,['Performs specialized Post Doctoral work in t...,['Demonstrated track record of published resea...,"['PhD in area of project specialization', 'Kno...",Not Mentioned,"['Resume', 'Cover Letter']",n
244,179544157,Peter B. Kenen Visiting Fellowship\n==========...,https://www.click2apply.net/wJedg5sDOwVpBTa5Tg4ja,2026-09-01 12:23:53.517,Peter B. Kenen Visiting Fellowship,Princeton University,"Princeton, NJ",Not specified in the text,Not specified in the text,['Pursue research on any topic in internationa...,['Current Ph.D. economist'],['Must hold a full-time position in a universi...,Not eligible for visa sponsorship,"['Resume', 'Cover Letter']",n

In [29]:
df.to_csv(
    "data/hedjobs.csv",
    index=False,
    lineterminator="\r\n",  # Ensures standard carriage return + line feed for multi-line cells
    encoding="utf-8",
)

In [11]:
with open("data/html_cache/cv/0.html", "r", encoding="utf-8") as f:
    html_content = f.read()
soup = BeautifulSoup(html_content, "lxml")

In [18]:
soup.find('title').string.split('|')[-1].strip()

'38039753'

In [20]:
attribs = ['job-description', 'company-information']
for attrib_id in attribs:
    attrib_div = soup.find(id=attrib_id)
    if attrib_div:
        attrib = md.markdownify(str(attrib_div))
        print(attrib)

Job Details
-----------

**Assistant Professor of Economics**

**Department of Economics**
**College of Business and Economics**
**Assistant Professor**
**Fall 2027**

The Department of Economics at California State University,
Fullerton (CSUF) invites applications for two tenure-track
assistant professor positions in Economics with a focus on
empirical research. We are particularly interested in candidates
conducting research using machine learning methods.

**Equal Opportunity and Excellence in Education and
Employment**This position is open and available to all
regardless of race, sex, color, ethnicity or national origin.
Consistent with California law and federal civil rights laws,
California State University, Fullerton (CSUF) provides equal
opportunity in education and employment without unlawful
discrimination or preferential treatment based on race, sex, color,
ethnicity, or national origin. Our commitment to equal opportunity
means ensuring that every student and employee has access to the
resources and support they need to thrive and succeed in a
university environment and in their communities. CSUF complies with
Title VI of the Civil Rights Act of 1964, Title IX of the Education
Amendments of 1972, the Americans with Disabilities Act (ADA),
Section 504 of the Rehabilitation Act, the California Equity in
Higher Education Act, California's Proposition 209 (Art. I, Section
31 of the California Constitution), other applicable state and
federal anti-discrimination laws, and CSU's Nondiscrimination
Policy. We prohibit discriminatory preferential treatment,
segregation based on race or any other protected status, and all
forms of discrimination, harassment, and retaliation in all
university programs, policies, and practices.

In addition, California State University, Fullerton is a leading
public university known for its strong academic programs and
commitment to student success. As one of the largest campuses in
the CSU system, Cal State Fullerton fosters innovation,
collaboration, and professional growth. The university values
teaching, research, and service, creating an environment where
students, staff, and faculty can thrive. Cal State Fullerton is a
designated Hispanic-Serving Institution and an Asian American and
Native American Pacific Islander-Serving Institution. The
university also received the prestigious Seal of Excelencia in 2021
and 2024 from Excelencia in Education, the nation's leading
authority on Latinx student success. Cal State Fullerton is an
equal opportunity employer with a diverse student population of
over 45,000 and a faculty and staff population of 4,000. Cal State
Fullerton is firmly committed to helping students achieve academic
excellence, career success, and economic mobility. Joining Cal
State Fullerton means becoming part of a dynamic team dedicated to
making a meaningful impact. We continuously seek individuals from
various disciplines who share the university's mission and core
values. We welcome you to consider joining the Titan community.

CSUF is committed to retaining all faculty and has established
affinity groups you can join to support your success.

**Position**CSUF faculty are committed
teacher/scholars who bring research and creative discovery to life
for students in classrooms, labs, studios, and individually
mentored projects. They teach broadly in the curricula of their
departments, advise students, and serve on departmental and
university-wide committees. The primary responsibilities of this
position will include developing and teaching undergraduate and
graduate courses in data analytics, as well as teaching core
graduate and undergraduate courses in the candidate's areas of
specialty. Faculty responsibilities also include contributing to
the supervision of undergraduate and graduate research. The
successful candidate will be responsible for producing scholarship
commensurate with the requirements for tenure. The successful
candidate will also be expected to contribute to and participate in
the life and development of the department, advise students, serve
on committees, and participate in the broader university and
disciplinary communities.

**Required
Qualifications**

* A completed Ph.D. degree in Economics at the start of the
  appointment.
* Expertise in applying modern econometrics and machine learning
  techniques to applied economic questions.
* Potential to publish academic research in leading
  journals.
* A commitment to high-quality teaching at the undergraduate and
  graduate levels and an interest in teaching a diverse student body,
  including first‐generation college students.

**Preferred Qualifications**

* The department has a preference for candidates who have
  developed and taught courses in data analytics/machine learning and
  who use these methods extensively in their research.

**Application**A complete online application
must be received by electronic submission to be considered. To
apply, please visit <http://hr.fullerton.edu/workforce/careers.html>,
choose full-time faculty, search for the position
**561939**, and provide the following required
materials:

* Cover letter in which you respond to the required
  qualifications.
* Curriculum vitae.
* Graduate Transcripts (Unofficial copies are sufficient for
  initial review.)
* Research statement with research sample(s).
* Teaching statement and evidence of teaching effectiveness if
  applicable.
* Candidate statement on commitment to inclusive excellence (no
  more than 500 words):
  + [Inclusive excellence](https://operations.du.edu/sites/default/files/2020-04/model-of-inclusive-excellence.pdf)
    is a strategic framework that recognizes the importance of
    diversity, equity, and inclusion in achieving organizational
    success and high-quality learning and teaching. It's a way of
    thinking and acting that integrates these values into all aspects
    of an institution, from curriculum and pedagogy to recruitment and
    hiring. Essentially, it means that excellence is not just about
    achieving high standards, but also about ensuring that all members
    of the community have the opportunity to thrive and contribute
    (Williams et al., 2005).
  + With the Inclusive Excellence Statement, we aim to learn about
    the applicant's perspective on their past and present contributions
    to and future aspirations for promoting and engaging with a diverse
    student population. This statement should showcase the candidate's
    professional experience, intellectual commitments, and/or
    willingness to teach and create an academic environment supportive
    of all students, including but not limited to those of diverse
    ages, abilities, cultures, ethnicities, gender identities,
    languages, religions, and sexual orientations.
  + [Cal State Fullerton](https://www.fullerton.edu/data/_resources/pdfs/institutional-research/csuf-facts-fall-25.pdf)
    serves a student body that reflects the rich cultural, ethnic, and
    socioeconomic mosaic of Southern California. Please provide
    concrete examples of how you, as a faculty member, will support our
    students in one or more of the following areas, which fall under
    the areas of awareness and understanding, experience and
    commitment, and future plans.
    1. Your contributions (past, present, or future) to embedding
       perspectives that are reflective of the student population into
       your teaching and/or scholarship.
    2. Your experience in service activities that are reflective of a
       diverse student population.
    3. Your experience and commitment to mentoring and providing
       opportunities to a diverse student body inside and outside the
       classroom environment.
    4. Your experience integrating creative activities that are
       inclusive of the identities of our student body and
       communities.
* A list of three references with relevant contact information:
* On the references page of the online application, enter
  information for three referents who will provide a confidential
  letter of reference for your application. They will receive a
  request via email along with information on uploading the letter at
  the appropriate step in the search process. Candidates can verify
  that each letter has been received by CSUF by logging back into the
  recruitment system.
* Applicants should be aware that recommendations will be used
  when evaluating candidates for the semi-finalist and finalist
  stage.

Please direct all questions about the position to: Pedro Amaral
at [pamaral@fullerton.edu](mailto:pamaral@fullerton.edu) or call
657‐278‐2588.

**Application Deadline**To be assured full
consideration, all application materials must be received by
**November 15, 2026**. The anticipated appointment
date is August 15, 2027.

**The College and Department**Composed of
over 20 tenured and tenure-track faculty and housed in the College
of Business and Economics, the Department of Economics offers BA
programs in Economics and in Business Administration with an
Economics concentration as well as a STEM-certified MA program. We
seek diverse faculty members who have a strong, ongoing commitment
to research and publication in high‐quality journals.

Located in one of the most vibrant and entrepreneurial business
communities in the United States, 26 miles from Los Angeles, the
College of Business and Economics at California State University,
Fullerton is the largest accredited business school on the West
Coast, nationally recognized for accreditation in both its business
and accounting programs.

The College provides a world-class business education, offering
graduate and undergraduate programs that integrate classroom
education with best business practices, technology, award-winning
research, functional applications, and real-world experience. Our
network of more than 60,000 alumni and business partners are the
driving force of Southern California business.

**Compensation**The Assistant Professor
(Academic Year) classification salary range is $6,221 to $13,224
monthly (12 monthly payments per academic year). The anticipated
hiring range is $9,100 to $9,278 per month.

Salary offered is commensurate with experience and
qualifications. In addition, the California Equal Pay Act prohibits
employers from paying its employees less than those of the opposite
sex and/or another race or ethnicity for substantially similar work
(<https://www.dir.ca.gov/dlse/california_equal_pay_act.htm>).

Summer research grants, moving expenses, start‐up funds, and a
reduced teaching load may be available.

**CSUF Benefits**An excellent comprehensive
benefits package includes health/vision/dental plans; spouse,
domestic partner, and dependent fee‐waiver; access to campus
child‐care; and a defined‐benefit retirement through the state
system and optional tax-sheltering opportunities. For a detailed
description of benefits, please visit <https://hr.fullerton.edu/total-wellness/>.

New employees hired by the CSU for the first time who first
become CalPERS members on or after July 1, 2017, are subject to a
10-year vesting period for retiree health and dental benefits.

**Additional Information**Multiple positions
may be hired from this recruitment based on the strength of the
applicant pool.

**International Candidates**California State
University, Fullerton, is not currently sponsoring any
**new** H-1B petitions for staff, management, or
faculty positions.

For tenure-track faculty positions, California State University,
Fullerton is currently **not** sponsoring H-1B
applicants subject to the $100,000 fee established by the
"Presidential Proclamation: Restriction on Entry of Certain
Nonimmigrant Workers" issued on September 19, 2025. Individuals in
the U.S. who hold a valid lawful nonimmigrant status visa can have
a petition filed on their behalf to change their status to H-1B
without being subjected to the fee. For example, the fee does not
apply to an H-1B petition filed by an individual presently in the
U.S. who is an F-1, J-1, or O-1 status holder.

**CSU Policies**The person holding this
position is considered a 'mandated reporter' under the California
Child Abuse and Neglect Reporting Act and must comply with the
requirements set forth in CSU Executive Order 1083, revised July
21, 2017, as a condition of employment.

A background check (including a criminal records check) must be
completed satisfactorily before any candidate can be formally
offered a position with the CSU. Failure to satisfactorily complete
the background check may affect the application status of
applicants or the continued employment of current CSU employees who
apply for the position.

Reasonable accommodations will be provided for qualified
applicants with disabilities who self‐disclose.

[Notice of
Non-Discrimination based on Gender or Sex and Contact Information
for Title IX Coordinator](https://www.fullerton.edu/civilrights/).

In accordance with the California State University (CSU)
Out-of-State Employment Policy, the CSU is a state entity whose
business operations reside within the State of California. It
requires hiring employees to perform CSU-related work within the
State of California. The employee must be able to accept on-campus
instruction, as assigned, and come to campus when needed. The CSU
also prohibits hiring and retaining employees working permanently
from a business location outside of the United States.

Applicants will be required to disclose whether they have
received a final administrative decision or final judicial decision
determining that they have committed sexual harassment within the
last 7 years only after a determination is made that they meet the
minimum qualifications for the position, and before an offer of
employment is extended. Applicants who reach the final stages of
the application process must also sign a release form that
authorizes the release of information by the applicant's current
and/or former employers to the CSU concerning any substantiated
allegations of misconduct.


**To apply, visit [https://careers.pageuppeople.com/873/fl/en-us/job/561939/assistant-professor-of-economics](https://apptrkr.com/9832475)**
je-6a319b45535b47fe8c5bcff88363d1f8
Company
-------

Cal State Fullerton is a leading campus of the CSU, serving as an intellectual and cultural center for Southern California and driver of workforce and economic development. We are an emerging national model for supporting student success through innovative high-impact educational and co-curricular experiences, including faculty-student collaborative research.

California State University, Fullerton offers a comprehensive and competitive benefits package. From our health plans and continuing education opportunities to our flexible spending accounts, survivor protection, leave programs and competitive retirement/savings plans, the CSU offers benefits that matter to you at each stage of your career.

Cal State Fullerton recognizes the balance of work and personal challenges.  We support these multiple roles, promote flexibility, and strive to enhance the overall experience for our employees.

At Cal State Fullerton, we take immense pride in our campus, where every employee is driven by a shared purpose: to transform lives through the power of education. We are committed to fostering an exceptional employee experience where you will be a catalyst for change.

California State University, Fullerton (CSUF)  is a diverse community of individuals who represent many perspectives, beliefs and identities, committed to fostering an inclusive, respectful, and intellectually vibrant environment. We cultivate a culture of open dialogue, mutual respect, and belonging to support educational excellence and student success. Through academic programs, student organizations and activities, faculty initiatives, and community partnerships, we encourage meaningful engagement with diverse perspectives. As a higher education institution, we are dedicated to advancing knowledge and empowering individuals to reach their full potential by prioritizing inclusive curriculum development, faculty and staff training, student mentorship, and comprehensive support programs. At CSUF, excellence is built on merit, talent, diversity, accessibility, and equal opportunity for all.

In [23]:
apply_link = soup.find('a', attrs={'data-hook': 'apply-button'})

# Get the href URL
url = apply_link['href']
print('jobs.chronicle.com' + url)

jobs.chronicle.com/apply/38039753/assistant-professor-of-economics?LinkSource=JobDetails

In [24]:
pattern = r'"datePosted"\s*:\s*"([^"]+)"'
tag = soup.find('script', string=re.compile(pattern))
if tag:
    html_content = str(tag.string)
    match = re.search(pattern, html_content)
    if match:
        date_posted = match.group(1)
        print(date_posted)
print("Not found")

2026-09-16T04:00:00.000Z
Not found